### ISSUE TITLE
App directory files location?

### ISSUE THREAD

**Issue by lincdh** [itinance/react-native-fs#1005]
Summary
I am trying to transfer files from my pc to the react native app directory which should be in My PC\Redmi Note 8 Pro\Internal shared storage\Android\data(USB plugged to phone) but there is no directory like com.my_react_native_app exsiting.

Other installed apps on my phone like Facebook, Google have those directories:

image

When I try console logging documentDirectory, it shows emulated/0/... folder which i'm not able to access through usb pc file transfer.

What should I do for the app to automatically created the app directory in real device or emulator and it's visible for user to transfer file?

Any help is really appreciated! Thanks!

What platform(s) does this occur on?
Android

Environment
System:
OS: Windows 10 10.0.19041
Binaries:
Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
npmPackages:
"react": "17.0.1",
"react-native": "0.64.0",
Devices:
Xiaomi Note 8 Pro

Reproducible demo or steps to reproduce from a blank project
I created a bare react native app and use expo file system

Run the app on my Xiaomi Note 8 Pro

Plug your my phone to PC through USB

Observe there is no com.my_react_native_app directory existed in the phone storage.

**Comment by venkatesh-inspiredge** [comment]
Hie @lincdh have you found any solution for it?

**Comment by RFG-G** [comment]
And what is the solution?

**Comment by lincdh** [comment]
Use storage access framework
