### ISSUE TITLE
Why is `size` a string and not a number?

### ISSUE THREAD

**Issue by robrechtme** [itinance/react-native-fs#1033]
Why is `size` on `ReadDirItem` and `StatResult` a string? Will it ever contain something other than a number, or can I safely parse it to an int? 🙂

**Comment by reviewher** [comment]
Best guess? representation issues.  Before `BigInt`, JS had no native support for 64-bit integers.  `Number` is IEEE754 double and cannot exactly represent integers larger than `2 ** 53 - 1`.  iOS API [`NSFileSize`](https://developer.apple.com/documentation/foundation/nsfilesize) uses a 64-bit `unsigned long long`.  It seems to be safe to `parseInt` the result with radix 10

**Comment by robrechtme** [comment]
Thanks for the info and sorry for the late response 😁 .
