### ISSUE TITLE
hope add lastModified

### ISSUE THREAD

**Issue by cdmalcl** [itinance/react-native-fs#104]
hope that:
        `fileMap.putString("last_mod", Long.toString(childFile.lastModified()));` or more

**Comment by johanneslumpe** [comment]
@cdmalcl I'm sorry but could you please re-phrase your issue properly? :)

**Comment by cdmalcl** [comment]
We need to obtain the modified time of the file, in order to achieve some special functions, such as sorting, classify, and other. This needs to return the list of files have lastmodified this property, the total can not obtain the file one by one to get.

**Comment by skizzo** [comment]
This would indeed be handy!

**Comment by itinance** [comment]
This will be solved with https://github.com/itinance/react-native-fs/pull/283, which is in test now and will be published in upcoming days :)
