### ISSUE TITLE
read file error Error: Invalid UTF-8 detected

### ISSUE THREAD

**Issue by Sean-Snow** [itinance/react-native-fs#106]
this is my code:
    try {
      file = await fs.readFile(path);
      console.log(file);
    } catch (e) {
      console.error(e);
    }

i got error:
Error: Invalid UTF-8 detected

**Comment by cjdell** [comment]
@Sean-Snow Perhaps the file is not encoded as UTF-8, but maybe as binary or ASCII? Have you tried specifying a different encoding as per the readme?

**Comment by franzejr** [comment]
@Sean-Snow, have you ever tried:

```
RNFS.readFile(path, 'utf8');
```

**Comment by cjdell** [comment]
@Sean-Snow @franzejr `readFile` defaults to `utf8`, I think it might need to be read as `binary` or `ascii`, or the file might corrupt or truncated.
