### ISSUE TITLE
Cannot read property 'readDir' of undefined

### ISSUE THREAD

**Issue by johnphillips1992** [itinance/react-native-fs#108]
I get the error message: "Cannot read property 'readDir' of undefined"

When I add this line: 
var RNFS = require('react-native-fs');

I am testing on the IOS simulator.

**Comment by savelichalex** [comment]
Are you sure that linking RNFS.xcodeproject right?

**Comment by pixelgamma** [comment]
Same error here. I've linked everything using rnpm link react-native-fs

**Comment by johanneslumpe** [comment]
Is this still an issue with the new 1.5 release?

**Comment by mkraft** [comment]
@johanneslumpe I'm blocked by this issue in 1.5.1.

**Comment by johanneslumpe** [comment]
@mkraft are you linking the project correctly? It seems a bit weird to me, because else we'd have quite a few more issues about this.

**Comment by cjdell** [comment]
@mkraft @johanneslumpe I agree, this smells of the native module not being loaded into memory. Can you triple check that you have linked the .a file with the binary in Build Phases?

**Comment by matdehaast** [comment]
You need to run react-native run-android/run-ios after installing before you can just reload the javascript. Reason being the module has native components that will not be installed yet if you do not do a full build first

**Comment by npomfret** [comment]
I get a similar problem in android, but only on an app that's deployed to the app store.  It crashes immediately (in android).  Works fine in dev mode

```
07-29 09:07:27.915 23705-23746/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   com.facebook.react.modules.core.JavascriptException: undefined is not an object (evaluating 'i.readDir'), stack:
                                                   <unknown>@629:187
                                                   o@2:517
                                                   e@2:326
                                                   i@2:188
                                                   <unknown>@628:299
                                                   o@2:517
                                                   e@2:326
                                                   i@2:188
                                                   <unknown>@365:1403
                                                   o@2:517
                                                   e@2:326
                                                   i@2:188
                                                   <unknown>@12:101
                                                   o@2:517
                                                   e@2:256
                                                   i@2:188
                                                   global code@635:9
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:94)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
                                                       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
                                                       at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
                                                       at java.lang.Thread.run(Thread.java:856)
07-29 09:07:27.945 1654-1673/? E/android.os.Debug: !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error
```

**Comment by macdabby** [comment]
Same issue here.  I tried the github repo then I get this:

Unhandled JS Exception: undefined is not an object (evaluating 'RNFSManager.NSFileTypeRegular')

I think it's from here: https://github.com/johanneslumpe/react-native-fs/blob/master/FS.common.js#L17

I have rnpm installed but it also throws an error, but i did verify that both the library and the link are configured in xcode

**Comment by macdabby** [comment]
I am having a similar issue with another module, so I think this might be an issue outside of this module - possibly undocumented or broken in react native

**Comment by macdabby** [comment]
Ok, I found part of the issue was that the files weren't included right. If you are using Deco to build the app, after you do all the xcode includes for the libraries, you also have to tell Deco to 'Build Native Modules'
<img width="342" alt="screen shot 2016-08-08 at 2 09 29 pm" src="https://cloud.githubusercontent.com/assets/176957/17497866/da447ecc-5d78-11e6-9fc7-485f78337b7f.png">

**Comment by jernejrus** [comment]
Using version 1.5.1 with react-antive 0.29.2. Did the rnmp link. iOS works smoothly, have the same problem on Android.

**Comment by thejessma** [comment]
I have this issue as well. I've installed with XCode and I added the line "var RNFS = require('react-native-fs');". When I run 'react-native run-ios', I get this error:
 
Unhandled JS Exception: undefined is not an object (evaluating 'RNFSManager.NSFileTypeRegular')

However, when I run the project directly from XCode, I don't have this error?

**Comment by michaelswe** [comment]
Same here.
Works when I run from XCode, but does not work from command line (react-native run-ios).

- I closed the packager and XCode before linking rnfs
- Also tried to clear the cache `npm start --reset-cache`
- Tried to both manually linking and `react-native link react native-fs`

RN 0.32
RNFS 2.0.1-rc.2 (got it straight from npm)

I have a couple of other native packages which runs fine:
- react-native-camera
- react-native-permissions

**Comment by michaelswe** [comment]
Just to ensure I have done the right thing.
What does the asterisk indicate in the linking instructions?

> Add the lib*.a from the RNFS project

I added a file called **libRNFS.a**. Is this the file referred to as **lib*.a**?

**Comment by michaelswe** [comment]
Same problem with RNFS 1.5.1.
Steps:

1. `react-native unlink react-native-fs`
2. `npm install https://github.com/johanneslumpe/react-native-fs.git#1.5.1 --save`
3. Link manually according to instructions

Runs fine from XCode but not from command line.

I really need to handle some files in my caches folder. Are there no other alternatives than RNFS for React Native?

Unfortunately, I don't have the knowledge to dig deeper into the code. Please instruct me if anyone needs more test data. The problem is totally reproducible at my computer.

**Comment by michaelswe** [comment]
SOLVED.

I upgraded from RN0.32 to 0.33. Either the new RN version made it work or the fresh xcode-proj I got after `react-native upgrade`. I'm guessing the latter.

Here is what I did:

1. `npm install react-native@0.33`
2. `react-native upgrade`
3. Answered Y on every replace file question
4. Relinked my native libraries, i.e. `react-native link react-native-fs` 

If you don't want to upgrade RN I'd guess that your linking problems will be solved by just following steps 2-4.

**Comment by logileifs** [comment]
I'm getting the same error on android with a fresh install of RN 0.34.1.

`undefined is not an object (evaluation 'RNFSManager.RNFSFileTypeRegular')`

Problem seems to be in line 17 in FS.common.js
`var RNFSFileTypeRegular = RNFSManager.RNFSFileTypeRegular;`
Where RNFSManager is for some reason not imported

**Comment by logileifs** [comment]
Does anyone know what has changed in RN 0.34.1 to cause NativeModules not to include RNFSManager ? Or if there is possibly another explanation? I have already verified that the module is linked.

**Comment by logileifs** [comment]
I followed @michaelswe's instructions and got it working so it seems this component is not working with latest react native version (0.34.1). Any ideas how to get it working? If someone can point me in the right direction I might be able to submit a pull request

**Comment by johanneslumpe** [comment]
Unfortunately I cannot set aside any of my time to work on this library :/

**Comment by logileifs** [comment]
@johanneslumpe no problem, I was hoping maybe someone of the other contributors knew something about the issue

**Comment by logileifs** [comment]
I realized this was a linking error. Somehow it got linked correctly when I used RN 0.33 but not RN 0.34. After installing again in a RN 0.34 project and manually linking I got it working just like with 0.33

**Comment by alfonsodev** [comment]
I had the same issue, in my case 
```
01-08 04:56:28.183 1742-1788/com.ghinwa E/ReactNativeJS: undefined is not an object (evaluating 'RNFSManager.readDir')```
This problem is solved following the "Usage (Android)" guide in the README.md for your exact version of react-native.
👍
