### ISSUE TITLE
Open file error: Out of memory

### ISSUE THREAD

**Issue by aldobel** [itinance/react-native-fs#1081]
Hi everyone, I'm trying to open a file (playlist) saved on the phone memory, but when I try to process it on android, it gives me the error as in the object. How can I solve? I use react-native-document-picker
this library to open the documents and this code to process the file:
```
async (e) => {
          RNFS.readFile(result[0].uri)
            .then((res) => {
              console.log("GOT RESULT", res);
            })
            .catch((err) => {
              console.log('Errore locale: ',err);
            });
```

**Comment by aldobel** [comment]
Hi all, I solved my problem using ``` RNFS.read (path, sizeElementSelected) ```. Thanks

**Comment by dianamelga** [comment]
Hi @aldobel , what value you set for `sizeElementSelected` ?
