### ISSUE TITLE
Pod depends on React 0.11.0?

### ISSUE THREAD

**Issue by PimDeWitte** [itinance/react-native-fs#116]
<img width="936" alt="screen shot 2016-06-14 at 12 22 53 pm" src="https://cloud.githubusercontent.com/assets/8763534/16056529/bb8a67fe-322a-11e6-9cf9-8275194c6df5.png">

Whenever I run "pod install" it also installed React 0.11.0, is this supposed to happen?

**Comment by richard-sim** [comment]
Same question here..

**Comment by tarkanlar** [comment]
+1

**Comment by aaronbuchanan** [comment]
looking for the same answer

**Comment by brianlaw033** [comment]
+1
