### ISSUE TITLE
can't access the files stored in document directory path

### ISSUE THREAD

**Issue by saikrishnanamburi** [itinance/react-native-fs#1173]
I am developing react-native android application. where I am able to store the files in document directory but I can't access those files.
I have these permission
"android.permission.WRITE_EXTERNAL_STORAGE"  and  "android.permission.READ_EXTERNAL_STORAGE" 

I am using android 11.

**Comment by pruthvirajkarurcodewave** [comment]
@saikrishnanamburi Were you able to resolve it ?

**Comment by saikrishnanamburi** [comment]
yes

**Comment by arnabdotpy** [comment]
@saikrishnanamburi can you please share the solution here?
