### ISSUE TITLE
Suggestion: add md5, sha file checksum operations. 

### ISSUE THREAD

**Issue by mmmurf** [itinance/react-native-fs#125]
This would be a great addition to this library, in my opinion.  If it is something you would want, and if nobody else can easily add it, I'll submit a PR.

**Comment by tsemerad** [comment]
I agree this would be a great addition.

**Comment by itinance** [comment]
Just use the [hash](https://github.com/itinance/react-native-fs#hashfilepath-string-algorithm-string-promisestring)-function.
