### ISSUE TITLE
Android - MainBundlePath - Is there a way to read files from Resources, just the way we have it in iOS?

### ISSUE THREAD

**Issue by abhaytalreja** [itinance/react-native-fs#132]
This is more of a question than a bug. Also, it may turn out to be an enhancement depending on your thoughts.

**Comment by johanneslumpe** [comment]
I have to direct this to @cjdell as I haven't written any of the Android code.

**Comment by abhaytalreja** [comment]
@johanneslumpe @cjdell - There is a PR for having access to the Android Assets, can that be looked upon? https://github.com/johanneslumpe/react-native-fs/pull/83
