### ISSUE TITLE
cannot read property of RNFSFileTypeRegular of undefined

### ISSUE THREAD

**Issue by patricktresp** [itinance/react-native-fs#190]
Hi all,

i am having issues using this module in an ios project. 
The Error occurs inside the module, therefore i assume, some dependencies // linkages are incorrect?
in FS.common.js this line of code throws the error 'cannot read property of RNFSFileTypeRegular of undefined'

`var RNFSFileTypeRegular = RNFSManager.RNFSFileTypeRegular;`

Meaning that RNFSManager is undefined. How is this possible?
RNFSManager is created here : 
`var RNFSManager = require('react-native').NativeModules.RNFSManager;`

I guess, NativeModules does not have the RNFSManager included wich is the reason for this error.
Does anyone know, how to fix this?

( works properly in android - must be an ios only issue ?)

i am using 
react-native-cli: 1.0.0
react-native: 0.35.0

thnx for any help on that!

**Comment by iotashan** [comment]
I had this issue on Android, and it was because I didn't link the module properly.

**Comment by popozy** [comment]
I have met the problem on Android as well.  So how can we fix the bug?

**Comment by iotashan** [comment]
You fix the bug by reading and following the instructions correctly 😄 

Seriously, I hit the error, and found out I skipped a step in the setup.

**Comment by popozy** [comment]
Ah.....I found my mistake, thx(I do not new the RNFSPackage in java code):)

**Comment by BG687** [comment]
I am also getting the same error. Followed the instructions in the ReadMe three times and linked via rnpm. It says that the library is linked successfully, yet I am getting the above error in my simulator. 

I am also getting this error in XCode: "App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file." Has anyone encountered this / have any ideas? -- would be much appreciated.

**Comment by iotashan** [comment]
Http errors would be unrelated to rnfs. The error happens when you make an insecure http request without exempting it in info.plist

If you aren't making any network requests, then it's the debug build of the app trying to connect to the packager.

**Comment by BG687** [comment]
Thanks for the response, that is helpful. Any suggestions for the other error (RNFSManager is undefined)... I have tried many things, including using an older version of React Native, using older version of react-native-fs, npm installing directly from the github repo, etc etc.

**Comment by iotashan** [comment]
I would manually go through the steps instead of rnpm then. The cause of the bug is always that all steps were not completed.

**Comment by smkhalsa** [comment]
@BG687 I was having the same issue. What worked for me was to build the debug scheme in XCode, then retry using react-native run-ios.

**Comment by lengocgiang** [comment]
anybody have solution for this ?

**Comment by jjhesk** [comment]
I also have the error from #258

**Comment by Thibaut-Fatus** [comment]
This issue is still present on RN 0.41 / iOS (android works)

I've tested both 2.0.1-rc.2 and 2.1.0-rc.1:
- automatic link seems to goes through all steps, but still shows the error
- manual link does not work either

We're on xcode 7.3.1

**Comment by volodymyrlut** [comment]
I am also facing this issue. 
My tool set is same as @Thibaut-Fatus use.

**Comment by ruler47** [comment]
@Thibaut-Fatus, @volodymyrlut +1

**Comment by volodymyrlut** [comment]
@ruler47 @Thibaut-Fatus well, guys, I believe you should rebuild your Xcode project running `react-native run-ios`. This resolved my issue yesterday without manual linking and the stuff.

**Comment by Thibaut-Fatus** [comment]
We've also tested after updating to xcode 8.2, same issue (cleaning project / rebuilding / removing node_modules / manual & automatic linking), still does not work.

However, since our goal was to display PDF, we ended using platform specific code and WebView on IOS (PDF not supported yet in Android)

**Comment by iotashan** [comment]
It's working for me fine on iOS RN .40 and xCode 8.x.newest

**Comment by loloof64** [comment]
I had also this error on my Android emulator but it was because I did not restart gradle build (with `react-native run-android`). It worked without manual configuration but with `react-native link`.

**Comment by dan-me** [comment]
re-run  ``` react-native run-android ```  or ``` react-native run-ios```

**Comment by luskin** [comment]
I don't know why this fixed it but I removed libRNFS.a from Link Binary with Libraries and re-added it and now it's working.... go figure...

**Comment by pacozaa** [comment]
@iotashan Thanks

**Comment by Xing-He** [comment]
` automatically link`  doesn't add `RNFS` to  my  project,  i  add it `manually` to resolve this issue!

**Comment by ashishlamse** [comment]
restart xcode or close your project tab clean and rebuild.

**Comment by njt1982** [comment]
Same here as @Xing-He  - I followed the instructions and the `react-native link` did not add the XCode project or the linked binary. I had to manually do it. Problem solved.

**Comment by franck-nadeau** [comment]
I had this problem on iOS after running ```react-native link``` to link another unrelated module after installing RNFS. 

To fix this, I had to re-run:

```pod update```

so that it reinstalled the RNFS pod, then rebuild and install the app. I don't know why it got removed, but this fixed my problem without having to relink the lib.

**Comment by addismiraph** [comment]
> re-run `react-native run-android` or ` react-native run-ios`

Works.

**Comment by e-monson** [comment]
@iotashan Is there a specific step that you've found people usually skip when experiencing this issue?

**Comment by abumubaarak** [comment]
`packages.add(new RNFSPackage());`
For react-native 0.29.0 and higher

**Comment by Rhym** [comment]
For reference for people in the future, I had to add this line to my `MainApplication.java` file:

```java
// ...
@Override
protected List<ReactPackage> getPackages() {
  @SuppressWarnings("UnnecessaryLocalVariable")
  List<ReactPackage> packages = new PackageList(this).getPackages();
  packages.add(new RNFSPackage()); // <----------- THIS_LINE_HERE
  return packages;
}
```

And that fixed the issue.

**Comment by pkatheti** [comment]
for windows desktop application give me sol

**Comment by fuyuwin** [comment]
> You fix the bug by reading and following the instructions correctly 😄
> 
> Seriously, I hit the error, and found out I skipped a step in the setup.

Lol I know that this is a old thread but, what a rude answer -.-

**Comment by whoproami** [comment]
i have question why is this happening till now.

![Image](https://github.com/user-attachments/assets/3d9a0702-1185-4a94-8116-2d18edec57a9)

**Comment by whoproami** [comment]
i am facing this issue in 2025 also.
