### ISSUE TITLE
Issue with readDir method

### ISSUE THREAD

**Issue by Okipa** [itinance/react-native-fs#207]
I get an issue with the readDir method.

When the directory does not exists, I catch an error normally but just after, I get the following exception that is not catched :
`ExceptionsManager.js:82 RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSError)`
Would you have an idea from where it is coming from ?

I try to access this path : RNFS.DocumentDirectoryPath + '/photos'. It doesn't exists when the app is just installed, which is normal (the folder is created on the first photo storage).

To avoid this problem, I would like to test if my directory exists but it does not works with the exists method that only test files.

Thanks by advance for your support.

**EDIT :**
Here is my code :

```
    // we set the promise
    const deferred = q.defer();
    // we set path where are stored the photos to upload
    const dirPath = fs.DocumentDirectoryPath + '/photos_to_upload';
    // we get the photos
    fs.readDir(dirPath).then((photos) => {
      const promises = [];
      _.each(photos, (photo) => {
        const promise = PhotoService.uploadPhoto(sessionToken, photo);
        promises.push(promise);
      });
      q.allSettled(promises).then((results) => {
        ... [treatment] ...
        deferred.resolve();
      });
    }).catch((error) => {
      // we reject the main promise
      deferred.reject(error.message);
    });
    // we return the promise
    return deferred.promise;
```

**Comment by avclarke** [comment]
Was having the same issue @Okipa, try upgrading RN https://github.com/facebook/react-native/commit/c144bbfb7ebdd174707638eaa344a9fddb38f253
