### ISSUE TITLE
Support assets-library tag

### ISSUE THREAD

**Issue by apolkingg8** [itinance/react-native-fs#21]
Is there any chance to support assets-library tag url? ex: `assets-library://asset/asset.JPG?id=1A85E963-XXXX-XXXX-XXXX-A497490A93B9&ext=JPG`

**Comment by johanneslumpe** [comment]
@cjdell what do you think about this? Is there an equivalent for Android?

**Comment by cjdell** [comment]
@johanneslumpe Sorry for the late reply. Android's method of accessing assets is to use `file:///` URL. We could extend support to all URL formats supported by the platform, so long as it doesn't lead to ambiguities. I think both can convert URL to absolute path and vice versa.

Can we start some sort of wish list for requested features? I will be using this library in other projects so am happy to put the time in to improve it :-)

**Comment by johanneslumpe** [comment]
@cjdell sorry for not replying here - kind of forgot about it. I think a feature-request thread/list might be useful to consolidate things in a single place and then to figure out what's priority.

**Comment by superandrew213** [comment]
Anyone working on this?

**Comment by johanneslumpe** [comment]
@superandrew213 not to my knowledge

**Comment by shahen94** [comment]
I can't load image from `CameraRoll` on iPhone. 
assets-library://asset/asset.JPG?id=1A85E963-XXXX-XXXX-XXXX-A497490A93B9&ext=JPG.

Is it possible now ?

**Comment by superandrew213** [comment]
Not yet

**Comment by itinance** [comment]
This is done now by https://github.com/itinance/react-native-fs/pull/286: "copyAssetsFileIOS()"

**Comment by ObidosDev** [comment]
@itinance Hm, but what about video?!

**Comment by itinance** [comment]
Ah, good hint. I already have the code for video finished and use it in another app natively so far. 
Will put it into the library

**Comment by ObidosDev** [comment]
@itinance great! It was strange for me cause methods name mean that it can copy both video and audio

**Comment by mojocakes** [comment]
@itinance Is is now possible to use copyAssetsFileIOS() with videos? I'm not sure how to get this working. My videos are being saved as JPEG files :rofl:

**Comment by itinance** [comment]
For Videos another approach is required. I've already wrote the method in iOS, i still need to add the javascript-bridge. I will provide this on the Weekend.

**Comment by mojocakes** [comment]
Hi @itinance, sorry to bug you again! Have you had any luck getting this working? I appreciate your work buddy thanks in advance 😄

**Comment by prabhu133** [comment]
I have url something like this: 
assets-library://asset/asset.JPG?id=98EBA95A-254E-40F4-8E1D-C355D8795777&ext=JPG'

I need to convert it to something like this :
'content://media/external/images/media/30993'.

Can I make use of this copyAssetsFileIOS( ) and pass this asset-library url as param.?
