### ISSUE TITLE
[Question] Accessing result with async/await

### ISSUE THREAD

**Issue by Proberts** [itinance/react-native-fs#211]
I'm doing this:

`b64data = await RNFS.readFile(path, 'base64');
console.log(b64data);`

Which works great. readFile returns a resolved Promise and the base64 file is stored as a string in a member variable called "_65".  What's the correct way to access the returned base64 string? In fetch API, for example, there's .text() and .json() that get the result from the promise, but I don't see any similar functions in rnfs.

**Comment by itinance** [comment]
It depends what you really want to do. 
For decoding base64-data you can yes the npm module base-64 for decoding. Otherwise you can read the file as plain ascii or utf-8 to "`JSON.parse`" it
