### ISSUE TITLE
Downloads can be both resolved and rejected.

### ISSUE THREAD

**Issue by DemisB** [itinance/react-native-fs#218]
Hello,

First of all I must thank you for this very nice and convenient module.

Recently I have noticed that, when you try to stop a download job with `RNFS.stopDownload`, the native code allows you to trigger the rejection of the download promise even if it has already been resolved.

![rnfs_issue](https://cloud.githubusercontent.com/assets/17614778/21006268/69a7154c-bd38-11e6-9c0b-fef36aa9cb79.png)

As of the Javascript side, it raises an exception which is quite difficult to understand (and which, fortunately, only occurs when `__DEV__` is true, see https://github.com/facebook/react-native/blob/master/Libraries/BatchedBridge/MessageQueue.js#L246-L271 ):

![rnfs_issue_emulator_snapshot](https://cloud.githubusercontent.com/assets/17614778/21006568/b3e050c8-bd39-11e6-8ba1-c6fa51f5b1b4.png)

Of course you might tell me, and you would probably be right: "If you try to stop something which is already over, you are exposed to unpredictable behaviours".
However it could be nice to have a safeguard in the native code which prevents this kind of exception to happen.

Hope this helps :)

**Comment by nbolender** [comment]
This PR resolves this issue: https://github.com/johanneslumpe/react-native-fs/pull/219
