### ISSUE TITLE
Release to CocoaPods

### ISSUE THREAD

**Issue by hugoduncan** [itinance/react-native-fs#22]
To help manage dependencies via [CocoaPods](https://cocoapods.org/), please consider releasing as a pod.

See [react-native-xml](https://github.com/artemyarulin/react-native-xml/blob/master/react-native-xml.podspec) as an example.

**Comment by johanneslumpe** [comment]
I haven't really worked with CocoaPods, so I will have to look into this when I get the time. Does CocoaPods require an account, just like npm? Does it provide a CLI for publishing easily?

**Comment by hugoduncan** [comment]
This seems to cover [publishing from the command line](https://guides.cocoapods.org/making/getting-setup-with-trunk.html).

**Comment by grabbou** [comment]
What is your use case @hugoduncan that the local podspec cannot full fill? In general I am a bit sceptical to this since React Native itself is no longer being published to CocoaPods separately.

**Comment by n8stowell82** [comment]
I would think support for rnpm would be best solution  @johanneslumpe is this a possibility?

**Comment by Elyx0** [comment]
It needs an update too for cocoapods-1.0.0

```
Fetching podspec for `RNFS` from `../node_modules/react-native-fs`
[!] The `RNFS` pod failed to validate due to 2 errors:
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | attributes: Missing required attribute `license`.
    - ERROR | attributes: Missing required attribute `summary`.
    - WARN  | license: Missing license type.
    - WARN  | source: Git sources should specify a tag.
```

**Comment by gre** [comment]
same error
