### ISSUE TITLE
Update README.md: 2.0.1-rc.3 breaks on RN < 0.40

### ISSUE THREAD

**Issue by a-koka** [itinance/react-native-fs#248]
README.md says to install via `npm install react-native-fs@2.0.1-rc.2 --save` for RN < 0.40. This works fine at first but any future `npm update` would update to `2.0.1-rc.3` and thus breaking the build.

README.md should be updated to instruct updating `package.json` to `"react-native-fs": "2.0.1-rc.2"`. Notice removal of tilde.

**Comment by itinance** [comment]
Done. Thanks for pointing out!
