### ISSUE TITLE
StatResult on iOS does not return name or path

### ISSUE THREAD

**Issue by Ignigena** [itinance/react-native-fs#252]
According to documentation, the `StatResult` object should return both`name` and `path` upon a successful stat. On iOS using the latest published NPM build this is not the case and those two values are missing:

```
2017-02-09 16:37:06.714486 redacted[7437:2536610] { ctime: Thu Feb 09 2017 16:37:03 GMT-0600 (CST),
  mtime: Thu Feb 09 2017 16:37:03 GMT-0600 (CST),
  size: 354772,
  mode: 420,
  isFile: [Function: isFile],
  isDirectory: [Function: isDirectory] }
```

**Comment by itinance** [comment]
i've updated the readme that name and path will not be returned.
