### ISSUE TITLE
Is there anyway to include the creation date of the file?

### ISSUE THREAD

**Issue by crysfel** [itinance/react-native-fs#253]
Hi folks!

I'm wondering if is possible to add the creation date of the file to the `readDir` method. It would be nice to include this information on the list of objects, currently we have `name`, `path` and `size` which is very useful, but I think the creation date should be there as well.

Any plans on adding this feature? Is it even possible to get this information from the file system on iOS and Android devices?

Regards

**Comment by Ignigena** [comment]
Needing this functionality myself and just submitted a PR for testing.

**Comment by itinance** [comment]
waiting for a [small change](https://github.com/itinance/react-native-fs/pull/265#pullrequestreview-34813768) [or discussion], then i will merge quickly

**Comment by itinance** [comment]
As with stat() there is now "ctime" and "mtime" available also in readDir(). Thanks to #283
