### ISSUE TITLE
Question: Enable background fetch

### ISSUE THREAD

**Issue by a-koka** [itinance/react-native-fs#266]
The docs say to `enable background fetch for your project in XCode` using the provided [link](https://www.objc.io/issues/5-ios7/multitasking/#background-fetch%3CPaste) where the following three steps are specified:

1. Enable background fetch in `Info.plist`
2. Set background fetch interval in `didFinishLaunchingWithOptions`
3. Add a callback like `performFetchWithCompletionHandler`

Do all three of these steps need to be performed manually? If I understand correctly, the callback may be implemented by `react-native-fs`. Is that correct?

**Comment by wootwoot1234** [comment]
I have the same questio.  Did you ever figure this out?

**Comment by a-koka** [comment]
No, I've been waiting on someone who may know the answer.

**Comment by wootwoot1234** [comment]
I'm going to try it out without doing step 3 on your list.  I'll report back but if I forget, remind me.

**Comment by wootwoot1234** [comment]
Yup, tested.  It works.  No need for the third step.

**Comment by a-koka** [comment]
Thanks for the update @wootwoot1234. Appreciate it! I'll leave this open for the authors to update the docs with this information.

**Comment by wootwoot1234** [comment]
It's an open source project, why don't you update the docs and do a pull
request. :)

**Comment by itinance** [comment]
as @wootwoot1234 said, will @a-koka propose the final solution into the readme that we can close this issue that way? :) thank you very much

**Comment by a-koka** [comment]
There you go guys!

**Comment by itinance** [comment]
Thanks a lot. Merged.
