### ISSUE TITLE
How to use downloadFile that can save file to album?

### ISSUE THREAD

**Issue by CandyKTN** [itinance/react-native-fs#268]
const ret = RNFS.downloadFile({ fromUrl: url, toFile: downloadDest, begin, progress, background, progressDivider });

 I want to get the album path : downloadDest

**Comment by itinance** [comment]
I don't know how it is on android, but on iOS there is no special path where you can place files to include them into the photo album.
But i think about to add a special method in RNFS to achieve that. More information according to this issue can you read here: https://github.com/itinance/react-native-fs/issues/281#issuecomment-298115758

**Comment by itinance** [comment]
You can download this File to a temporary Directory (using the constant `RNFS.TemporaryDirectoryPath`) and put it into the Album using official [CameraRoll.saveToCameraRoll](https://facebook.github.io/react-native/docs/cameraroll.html)

**Comment by CandyKTN** [comment]
@itinance Thanks

**Comment by flyskywhy** [comment]
> You can download this File to a temporary Directory (using the constant `RNFS.TemporaryDirectoryPath`) and put it into the Album using official [CameraRoll.saveToCameraRoll](https://facebook.github.io/react-native/docs/cameraroll.html)

I used `CameraRoll.saveToCameraRoll` to save RNFS.DocumentDirectoryPath/origin.gif generated by my APP PixelShapeRN, and found the saved.GIF by `CameraRoll.saveToCameraRoll` is smaller and more blurry and only just 1 frame, like a jpeg format.

So ref to https://github.com/itinance/react-native-fs/issues/897#issuecomment-759577180 , thus I can [let .gif file saved with my APP PixelShapeRN running on iOS be located on the device with my APP and other APP](https://github.com/flyskywhy/PixelShapeRN/commit/a38fc3f06a9a20b116c453425b031a71aa6a8234),  for example iOS "File Explorer" app now can find the .gif file and show for user.
