### ISSUE TITLE
undefined is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')

### ISSUE THREAD

**Issue by barzev** [itinance/react-native-fs#272]
I get the following error in RN 0.41.2: `undefined is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')` 

I'm trying to use the library in iOS only!

I have linked `react-native-fs`:
`rnpm-install info Android module react-native-fs is already linked 
rnpm-install info iOS module react-native-fs is already linked `

Can you help with that? 

Thanks!

**Comment by iou90** [comment]
You should rebuild app.

**Comment by thanhnhan2tn** [comment]
I have same issue with JEST testing.

**Comment by itinance** [comment]
Any news on this? Could you solve in the meanwhile, @barzev?

**Comment by barzev** [comment]
I'm sorry, I solved my problem by going a completely different route.

**Comment by JonathanKirknes** [comment]
I have this issue, too. Anyone can help me?

**Comment by cesarve77** [comment]
+1

**Comment by zGuindouGit** [comment]
I have this issue, too. Anyone can help me?

I want to convert image to base64 by using react-native-fs this is my code : 

```
var RNFS = require('react-native-fs')

export default class Converter {

    constructor(img) {
        this.img = img;
    }

    convertToBas64() {
        return awaitRNFS.readFile(this.img, 'base64').then();
    }

}
```
But the error undefined is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')  was appeared

**Comment by itinance** [comment]
Pls retry the full setup from scratch. This error is mostly caused with a not-linking of native modules.

Also don't forget to recompile and restart your whole project. Just a refresh is not sufficient.

@zGuindouGit in ypur code is also a space missing between await and RNFS:

`
return awaitRNFS.readFile(this.img, 'base64').then();
                   ^^^
`

**Comment by mostafa** [comment]
Hi,

I've recreated the whole android and ios directories (ejected) but it does not work and return this:
```js
 TypeError: Cannot read property 'RNFSFileTypeRegular' of undefined
```
