### ISSUE TITLE
**DISCONTINUED** How to proceed anyways? I'd like to continue

### ISSUE THREAD

**Issue by itinance** [itinance/react-native-fs#276]
This library was [discontinued](https://github.com/johanneslumpe/react-native-fs/commit/07017bb142b23b37c90820e9f2275a22e2466ddc) some days ago. Any ideas how to keep it alive? 18 open PRs, 44 Contributors... These numbers send a clear signal!

Since we make heavy usage of this lib in several projects, i'd like to continue this project. I know this code on all three layers (javascript, ObjectiveC, Java) very well and has debugged it quiet often. A switch to another library is currently not planned in our projects.

However, where to start to continue? 

§1 First i'd like to ask @johanneslumpe if he is interested to transfer the ownership to another person (e.g. me)? If not, am i allowed to continue this repo under a similar name like "react-native-fs2"?

§2 Second i renamed [my fork](https://github.com/itinance/react-native-fs2) (which is updated to the very last commit here on master) to "react-native-fs2" as a working title for now to be able to publish it on npm in upcoming days until a solution is in sight (currently it isn't published anyways). 

§3 Third, if §1 isn't possible, i'd like to ask authors of the recent, unmerged contributions to submit their PR to the "new" [library](https://github.com/itinance/react-native-fs2).

Any ideas? Answers? Questions?

**Comment by Antonhansel** [comment]
I hope the community can continue to work on this but I think it will depend on the reasons  @johanneslumpe stopped maintaining the project. Is it more about the time it takes ? Or is there something else ?

Thank you @johanneslumpe for your hard work and thank you @itinance for offering to continue the project!

**Comment by itinance** [comment]
Oh yes, thank you @johanneslumpe for this excellent work! I was totally shocked yesterday that i've forgotten to mention it separately in my opener :)

**Comment by johanneslumpe** [comment]
@itinance @Antonhansel I am not using react-native actively at work and my day job takes a huge chunk of my time, thus leaving no extra time to maintain this library. I haven't been able to keep up with all the changes to react-native and the codebase became stale rather quickly. Long story short: I can transfer ownership to @itinance but it would be nice if original credit would remain in place somehow. How does that sound?

**Comment by itinance** [comment]
Sounds great @johanneslumpe! Of course i will keep original credits.

**Comment by br4nnigan** [comment]
@itinance
what's the progress on this? I gotta decide whether to stick with this or not. At this point this lib is in a rather bad condition

**Comment by itinance** [comment]
Transfer is done. Thank you very much for your trust, @johanneslumpe, and once more for the awesome work on this library! 

Over the next days (and weeks for the complicated ones) i will view the open PRs and merge if valid and possible
