### ISSUE TITLE
support for containerURLForSecurityApplicationGroupIdentifier

### ISSUE THREAD

**Issue by npomfret** [itinance/react-native-fs#278]
I'm trying to implement a shared area of the file system between my app and an app extension using an App Group.  To access the path I need to read and write to a folder which I get access to by calling:

`NSString *path= [[[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:@"group.com.mygroupname"] path]`

Which returns something like:

`/Users/user/Library/Developer/CoreSimulator/Devices/some-id/data/Containers/Shared/AppGroup/some-other-id`

From what I can see in the docs there's no existing method for getting this data, is that correct?

**Comment by itinance** [comment]
Have you tried to call `stat()` or `exists() ` on exactly this path then and can leave here the result?

**Comment by npomfret** [comment]
I've submitted a PR that adds a function to return this path which has been accepted to master.  I'm using in my app and it's working fine.

**Comment by AkhilRaja** [comment]
@npomfret npomfret Could you please specify which method you've added to get the path ? Please specify some details ?

**Comment by npomfret** [comment]
https://github.com/wkh237/react-native-fetch-blob/pull/328
