### ISSUE TITLE
What's the correct syntax?

### ISSUE THREAD

**Issue by wootwoot1234** [itinance/react-native-fs#279]
What's the correct syntax (notice the `.promise` part)?  Or are they the same?  I've never seen the first example before but it works.  Just want to make sure I'm using the module right.

    RNFS.unlink(audioPath)
    .promise.then((result) => {  // <=================================
        console.log("audio removed success!");
    })
    .catch((error) => {
        console.log(error);
    });

or

    RNFS.unlink(audioPath)
    .then((result) => {  // <=================================
        console.log("audio removed success!");
    })
    .catch((error) => {
        console.log(error);
    });

**Comment by itinance** [comment]
unlink() returns already a promise, so this will be right syntax:

```
RNFS.unlink(audioPath)
.then((result) => {  // <=================================
    console.log("audio removed success!");
})
.catch((error) => {
    console.log(error);
});

```

Btw, your first approach with a separate property injection ".promise." should result in an exception because ".promise" is not defined.
