### ISSUE TITLE
incorrect version in package.json

### ISSUE THREAD

**Issue by ElvisChiang** [itinance/react-native-fs#282]
in 6232d4e

the prefix "v" make cocoapods fail
```
[!] Invalid RNFS.podspec file: Malformed version number string v2.1.0-rc.1.
```
Please remove the prefix "v" and release new npm
Thanks

**Comment by ElvisChiang** [comment]
oh~ 
already have a PR #264 for this

**Comment by benvium** [comment]
#264 has been merged.
