### ISSUE TITLE
childFile.lastModified needs to be coverted to string

### ISSUE THREAD

**Issue by MehdiZonjy** [itinance/react-native-fs#287]
Hello
I just created a fresh ReactNative project and installed the latest version (2.3.0). and i'm getting the following error 
`RNFSManager.java:262: error: incompatible types: long cannot be converted to String`

It seems that the problem is in the following line
`fileMap.putString("mtime", childFile.lastModified());`

 childFile.lastModified needs to be converted from long to string before adding it to the fileMap
The following fixes the issue
 `fileMap.putString("mtime", String.valueOf(childFile.lastModified()));`

**Comment by itinance** [comment]
Thanx for figuring out! Could you make a PR pls with your fix?

**Comment by itinance** [comment]
Fixed with "putInt" instead of "putString"

**Comment by itinance** [comment]
fixed with latest release

**Comment by MehdiZonjy** [comment]
sorry i was sleeping when you first replied and i just woke up so i couldn't make the PR.
thanks for the fix

**Comment by itinance** [comment]
You're welcome! I thought this would be a showstopper thats why i was acting fast :)
