### ISSUE TITLE
Delete mediaUri with the path 'content://media/external/images/media/#####'

### ISSUE THREAD

**Issue by Progoogler** [itinance/react-native-fs#295]
Currently I am able to use `RNFS.unlink('file path')`, but this only deletes the file on disk. 

How can I use RNFS to also delete the media content from the phone's gallery with the content path?

**Comment by Progoogler** [comment]
The way to do this is to use `let path = `${RNFS.ExternalDirectoryPath} /#####`` and then `RNFS.unlink(path)`; with ##### being the digit identifier.

**Comment by code-by** [comment]
there some placeholder / file with empty image remains in gallery till device reboot

**Comment by rashmimhatre100** [comment]
Any breakthrough to remove placeholder?

**Comment by cristiangustav0** [comment]
aaaaaaaaaaaaaa caralho
