### ISSUE TITLE
Android API 16 can't download

### ISSUE THREAD

**Issue by a-koka** [itinance/react-native-fs#306]
`downloadFile` throws the following error on API 16. Works well on API 24. Do we need to update `minSdkVersion` in `AndroidManifest.xml`?

```
Error downloading file /data/... Error: Unable to resolve host "some.host.com": No address associated with hostname
```

**Comment by a-koka** [comment]
It appears that my emulator can't access the internet at all. Non-issue here. My bad.

**Comment by kiranjd** [comment]
Got the same error. Also the same problem. Thanks
