### ISSUE TITLE
expected a map got a boolean constructing arguments for RNFSmanager

### ISSUE THREAD

**Issue by manuTro** [itinance/react-native-fs#311]
Hi, I just tried to use a real device (android) and I got this error

![screenshot_20170706-125800](https://user-images.githubusercontent.com/25326470/27908230-1eef63e8-624b-11e7-90f9-ca301a146095.png)

How I can fix it? (on the emulator I don't have it)

**Comment by itinance** [comment]
Please show some code and tell which versions you are using (RN + RNFS).

This is some example code which works out of the box, if the Linking of RNFS was done the right way:

```
RNFS.mkdir( RNFS.DocumentDirectoryPath + '/test').then( () => {
  RNFS.exists( RNFS.DocumentDirectoryPath + '/test').then( exists => console.log(exists))
}).catch( err => console.log(err))

```

**Comment by manuTro** [comment]
I found the mistake.. I did the upgrade of the library 2 months ago and it changes.. just the emulator didn't use it, so I didn't notice it before.
