### ISSUE TITLE
The file seems to have been downloaded successfully，But i can't find it in the folder.

### ISSUE THREAD

**Issue by quietautumn** [itinance/react-native-fs#313]
android version is ‘6.0.1‘
react-native version is  ‘ 0.43.1’
Here is the code：

        var formUrl = common.baseUrl+'/enclosures/IMG_20170617_093953.jpg';
        const downloadDest = `${RNFS.DocumentDirectoryPath}/IMG_20170617_093953.jpg`;
        const options = {
               fromUrl: formUrl,
               toFile: downloadDest,
               background: true,
               begin: (res) => {
                console.log(res);
            },
            progress: (res) => {

            }
        };
        try {
            const ret = RNFS.downloadFile(options);
            ret.promise.then(res => {
                console.log(res);
 
            }).catch(err => {
                console.log(err)
            });
        }
        catch (e) {
            console.log(e)
        }

**Comment by ngrj** [comment]
Hi, I'm not sure if you can view it from file manager, can u try this code to see content of document directory:
`RNFS.readDir(RNFS.DocumentDirectoryPath).then((res)=>{console.log(res)});`

This will verify your issue.

**Comment by quietautumn** [comment]
@ngrj @ngrj 
yes ，I can get an array，like this.
![e_o_lj3ue y jyu qzwh19](https://user-images.githubusercontent.com/16301518/28349798-86f0431e-6c77-11e7-9393-342a5788be4e.png)

**Comment by ngrj** [comment]
so the file exists, afaik it just that you can't access content of document directory from other applications, only your own application can access it.

**Comment by quietautumn** [comment]
@ngrj  Ok，thank you very much.
