### ISSUE TITLE
master branch needs createJSModules

### ISSUE THREAD

**Issue by a-koka** [itinance/react-native-fs#317]
I'm on react-native 0.44 and if I'm missing something new in the recent updates, I apologize. Thanks to @codesinghanoop for his recent fix to parallelize downloads. My app loads twice as fast now!

I've had to add the following to `RNFSPackage.java` to make things work using the `master` branch.

```
@Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }
```

**Comment by joshuapinter** [comment]
I had the same issue. I'm on react-native 0.46.4 and I need it as well. Creating a Pull Request now.

**Comment by codesinghanoop** [comment]
Is this working for you guys ?

**Comment by joshuapinter** [comment]
@codesinghanoop I added this to my fork and it solved the issue, yes.

**Comment by codesinghanoop** [comment]
ok cool 👍

**Comment by itinance** [comment]
I use RNFS on 0.45.1 without this line and it worked well.
How could that be?
I will merge anyways

**Comment by joshuapinter** [comment]
@itinance Not sure. Not sure when it started being required or not required. 

Does it work in your setup when you add this back in? I would assume that if it works without it, it would not work with it.

**Comment by a-koka** [comment]
Just upgrade to `react-native@0.46.4` and it's still required.

**Comment by joshuapinter** [comment]
I can confirm that. Running on 0.46.4 as well.

**Comment by joshuapinter** [comment]
@itinance Anything holding up the merge? Ran into this again today when doing a `yarn install` which wipes out local changes. Thanks.
