### ISSUE TITLE
Create multi folders in one API

### ISSUE THREAD

**Issue by hellomaya** [itinance/react-native-fs#320]
Hi, in case to create a folder, and many sub-folders, I am trying this way with current API:

```
const mkdirs =  (dirs) => {
    const tasks = [];
    for (let i = 0; i < dirs.length; ++i) {
       tasks.push(RNFS.mkdir(dir[i]));
    }
    return Promise.all(tasks);
}

RNFS.mkdir(path).then(()) {

   
}.catch (error) {

}
```

Could be an API to create a folder and its sub-folders once? Is it more efficient for this case too?

Thanks.

**Comment by itinance** [comment]
As for your subfolders pls refer to the README:

> Create a directory at filepath. Automatically creates parents and does not throw if already exists (works like Linux mkdir -p).


You need to pass only a /very/deep/path and all parents will be created automatically if still not present.

**Comment by hellomaya** [comment]
Thanks for your quick reply. In my case, I will create: 

- Main folder
  - FolderA
  - FolderB
  - FolderC
  - FolderD

In each of them, I could create more folders there, so it might be good to have this one.

**Comment by itinance** [comment]
How was it going, @hellomaya ?

**Comment by hellomaya** [comment]
Hi, @itinance, thanks for your asking. Due to the deliver time of the project, I am going to add this api for my personal use only, in Android, will just take an Array of paths, then create them same time, this will make my current app simple & efficient.

Your code is pretty clean & elegant, and make me easier to add this api, thank you!

I won't PR this change, as it's not in current codebase plan yet, but the source will be open in my forked repo.

```
RNFS.mkdirs(['/A/B', '/A/C', 'A/D', 'A/E']).then()...
```

**Comment by hellomaya** [comment]
Also if some methods was sync supported, will be efficient, a new RNRF.existsSync could be helpful. The case is, when using Image to show local disk image, will have to know if the Uri exist, if not, will throw Error in iOS, by using async exists, it will make all views difficult to do.
