### ISSUE TITLE
Error: Invalid continuation byte

### ISSUE THREAD

**Issue by frangeris** [itinance/react-native-fs#330]
Receiving this error when reading a file previously copied from iCloud...

```
Error: Invalid continuation byte
    at readContinuationByte (index.ios.bundle:57385)
    at decodeSymbol (index.ios.bundle:57411)
    at Object.utf8decode [as decode] (index.ios.bundle:57454)
    at index.ios.bundle:56828
    at tryCallOne (index.ios.bundle:6248)
    at index.ios.bundle:6334
    at index.ios.bundle:5803
    at Object.callTimer (index.ios.bundle:4967)
    at Object.callImmediatesPass (index.ios.bundle:5053)
    at Object.callImmediates (index.ios.bundle:5063)
```

Any advice?

**Comment by itinance** [comment]
Pls provide more information. Happens this one time with ONE specific file or with every file that comes from iCloud?

**Comment by frangeris** [comment]
Every file coming from iCloud, the content of the file is encoded using `Crypto.enc.Utf8` from [crypto-js](https://github.com/brix/crypto-js), related?

**Comment by frangeris** [comment]
@itinance For some reason the data returned is not valid, I'm receiving this

```javascript
RNFS.readFile(backup.path, 'base64')
  .then((content) => {
    console.log(content, atob(content))
  })
  .catch((err) => {
    console.log('error', err)
  })
```

```bash
// raw content
YnBsaXN0MDDTAQIDBAUGXE5TVVJMTmFtZUtleV8QEE5TVVJMRmlsZVNpemVLZXlfEBhOU1VSTEZpbGVSZXNvdXJjZVR5cGVLZXlcbG9ja3kuYmFja3VwEQGYXxAcTlNVUkxGaWxlUmVzb3VyY2VUeXBlUmVndWxhcggPHC9KV1oAAAAAAAABAQAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAeQ== 

// decoded using atob
bplist00Ó\NSURLNameKey_NSURLFileSizeKey_NSURLFileResourceTypeKey\locky.backup_NSURLFileResourceTypeRegular/JWZy
```

What is this? I just check the content of the file from iCloud and is totally different :s

**Comment by MossP** [comment]
@frangeris Did you find the cause of this? I've just stumbled upon it.
The file in my case was the ContentInfo.plist from an In-App-Purchase from an old App. Newer apps seems to be OK though.

**Comment by frangeris** [comment]
The issue **is not really related** with the `react-native-fs`, it's related with the way iCloud documents storage works, from [apple docs](https://developer.apple.com/library/content/documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesigningForDocumentsIniCloud.html):

> The first time your app adds a document’s on-disk representation to an iCloud (ubiquity) container, the system transfers the entire file or file package to the iCloud server, as shown in Figure 3-2. The first step is to send the document’s metadata, which includes information such as the document name, modification date, file size, and file type. 

That's what was happening to me, I was getting the metadata instead of the file content, so you have to "force" to download the document, something like this:

**NOTE:** notice this `.myfile.something.icloud`, if this file exists locally, the real file is not downloaded.... yet

```javascript
// files 
RNCloudFs.listFiles({
  targetPath: '.',
  scope: 'visible'
})
.then(result => {
  // any?
  if (result.files.length) {
    // is my file inside the list of files in iCloud?
    let backup = _.find(result.files, (o) => o.name.match(/myfile.something|.myfile.something.icloud/))

    // valid file?
    if (!backup)
      throw new Error('File not found in iCloud files')

    // downloaded?
    if (backup.name.match(/.icloud/)) {
      // force download the file
      Documents.downloadUbiquitousPath(backup.path)
        .then(() => this._decryptBackup(backup, password))
        .catch(() => {
          throw new Error('Error downloading file, not network?')
          // erro downloading from icloud
        })
    } else {
      // file is ready and downloaded
    }
  }
})
```

I'm using [react-native-cloud-fs](https://github.com/npomfret/react-native-cloud-fs) for access file in iCloud and [react-native-icloud](https://github.com/watert/react-native-icloud) as wrapper for iCloud calls.

Hope that help.... 🍺

**Comment by zi6xuan** [comment]
```
RNFS.downloadFile({
                fromUrl: sFile.url,
                toFile: filePath,
            }).promise.then((Result) => {
                if (Result.statusCode === 200) {
                    RNFS.readFile(filePath, 'utf8')
                        .then((text) => {
                             //read complete
                        }).catch((reason) => {
                            //Error: Invalid continuation byte
                        });
                } else {
                    //download failed
                }
                console.log('statusCode=' + Result.statusCode);
            });
```
I also encountered the same problem, can not be read after `downloadFile` download is completed

**Comment by brmk** [comment]
In my case, the encoding was not correct. The text file included é symbol, so I had to set "ascii" encoding to correctly read the file

**Comment by adeelcheeema** [comment]
This issue occurred when the file was not downloaded from iCloud.
Library used : **react-native-cloud-fs**
To download the file from iCloud add the following in the **node modules -> react-native-cloud-fs -> ios -> RNCloudFs.m**

```
RCT_EXPORT_METHOD(downloadFromCloud:(NSDictionary *)options
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject) {
    
    NSString *destinationPath = [options objectForKey:@"targetPath"];
    NSString *downloadedFilePath = [options objectForKey:@"cleanPath"];
    
    NSFileManager* fileManager = [NSFileManager defaultManager];
    NSError *error;
    [fileManager startDownloadingUbiquitousItemAtURL:[NSURL fileURLWithPath:destinationPath] error:&error];
    
    if(error) {
        return reject(@"error", error.description, nil);
    }
    
    bool isDownloaded = false;
    // Create a loop until isDownloaded is true
    while (!isDownloaded) {
        if([fileManager fileExistsAtPath:downloadedFilePath]) {
            isDownloaded = true;
        }
    }
    
    if(isDownloaded == true){
        return resolve(@{
            @"files": @true,
            @"path": downloadedFilePath
        });
    }
} 
```

Then call the function from the js code. 
`  RNCloudFs.downloadFromCloud({ targetPath: backup_path , cleanPath: full_path })`

- targetPath = path that contains .icloud extension
- cleanPath = path without .icloud extension or path you want to download the file (Recommended is a path without .cloud)
