### ISSUE TITLE
Can't upload ios file

### ISSUE THREAD

**Issue by lsorin81** [itinance/react-native-fs#331]
Failed to open target file at path 'file:///private/var/mobile/Containers/Data/Application/F72DE3C0-D0CF-417F-8326-053F5C0BD22C/tmp/xxxxxxxxxxxxxx-Inbox/pdftest.pdf',

Can't seem to find the file that I've just downloaded from Dropbox.
Please help!

**Comment by lsorin81** [comment]
removed "file:///" and made sure there were no spaces in file name!

**Comment by Mycatty** [comment]
Thanks for all
