### ISSUE TITLE
Where to write files too

### ISSUE THREAD

**Issue by kennetpostigo** [itinance/react-native-fs#332]
I'm creating a `.csv` file from data in my app. Where is the recommended place to store the file and retrieve it? I need to upload the file as an attachment for an email. The email API is from [react-native-mail](https://github.com/chirag04/react-native-mail).

**Comment by sampurcell93** [comment]
I think you want to look at fs.DocumentDirectoryPath

**Comment by fendorio** [comment]
@kennetpostigo Did you sort this?

Have a similar requirement, i'm getting blocked by a Gmail permission error currently, which I believe is down to the fact that Gmail can't access the DocumentDirectoryPath for an app.
