### ISSUE TITLE
use copyAssetsFileIOS copy video and save ,the new video was damaged.

### ISSUE THREAD

**Issue by cloudsafe** [itinance/react-native-fs#336]
use copyAssetsFileIOS copy video and save ,the new video was damaged.

**Comment by itinance** [comment]
Pls clarify "damaged". Was the file empty or not?
Have you [mediainfo](http://brewformulas.org/MediaInfo) installed? If not, it could be usefull for double checking such issues:

`brew install media-info`

With mediainfo you can alayze the saved videofile. If your app runs in iOS-simulator, you can simply reach the file from your terminal. If it was running on XCode, you need to export the "Container" in XCode -> Devices to get file access.

**Comment by cloudsafe** [comment]
not zero bytes size.and i haven't install media-info.My needs have been resolved.I convert the video file to base64 and save the file.and get the first frame.If the time is enough, I'll edit it by this program
