### ISSUE TITLE
Getting undefined is not an object (evaluating RNFSManager.RNFSFileTypeRegular) when using create-react-native-app

### ISSUE THREAD

**Issue by sw-yx** [itinance/react-native-fs#349]
Hi guys.. is RNFS compatible with CRNA? surprised nobody has asked this question before..

**Comment by Haggaish** [comment]
I get the same error

**Comment by Haggaish** [comment]
linking resolved the issue for me:
react-native link react-native-fs

**Comment by sw-yx** [comment]
important question: is it possible to link when inside CRNA?

**Comment by itinance** [comment]
IIRC Expo is not supporting any native libraries than their own.

**Comment by itinance** [comment]
Maybe this helps: "detaching from Expo", https://docs.expo.io/versions/latest/guides/detach.html
Closing this issue because Expo doesnt support native libraries per default. 

Pls feel free at any time to reopen or comment here new approaches if you find a solution.

**Comment by sw-yx** [comment]
sad, but thank you for helping me with a straight answer @itinance
