### ISSUE TITLE
RNFS.TemporaryDirectoryPath doesn't seem to return any files

### ISSUE THREAD

**Issue by slickdev** [itinance/react-native-fs#350]
"react": "16.0.0-alpha.12",
"react-native": "0.48.4",
"react-native-fs": "^2.5.1",

When I try the example code it works fine. If I replace RNFS.readDir(RNFS.MainBundlePath) with another item such as CachesDirectoryPath, etc. it works fine. However, when I try using RNFS.TemporaryDirectoryPath I receive the following error in console:

`Cannot read property 'path' of undefined undefined`

**Comment by ToJen** [comment]
Did you solve this @slickdev ?

**Comment by slickdev** [comment]
@ToJen this issue seems to be resolved, as I can use RNFS.readDir(RNFS.TemporaryDirectoryPath) now without issue. Closing
