### ISSUE TITLE
access content://com.android.providers.media.documents/document/image%3A99

### ISSUE THREAD

**Issue by EyalSi** [itinance/react-native-fs#351]
I'm getting a content uri in android while using react-native-document-picker or react-native-contacts (for the avatars).
URIs like:
'content://com.android.providers.media.documents/document/image%3A99'
Trying to access this file fails with "File does not exist"

const urlDecoded = decodeURIComponent(url);
RNFS.stat(urlDecoded)
        .then((file) => {
          console.log("RNFS URL SUCCESS", file);
        })
        .catch((err) => {
          console.log("RNFS URL ERROR", err);
        });

Any idea how to access the file?
10x

**Comment by itinance** [comment]
Hi @EyalSi! The scheme "content://" is currently not supported. 

PRs are very appreciated.

**Comment by LukBowen** [comment]
@itinance Does this still need to be resolved? I saw a PR request that could resolve it but I believe it was rejected?

**Comment by nzhtrtlc** [comment]
I have the same error, any updates ?

**Comment by LukBowen** [comment]
I have a fix locally in my project; however, I am hesitant to create a PR request since there is one that does the same already pending.

**Comment by itinance** [comment]
@LukBowen which one do you mean?

**Comment by LukBowen** [comment]
PR #49

**Comment by itinance** [comment]
Yes, i remember. I turned back to the contributor but he never answered. I will modify this PR manually to keep backward compatibility alive.

**Comment by LukBowen** [comment]
Sorry, I didn't realize that was it was missing backwards compatibility. Other wise I would have just create my own PR.

**Comment by itinance** [comment]
Submitting your own PR would be a good option! I would merge quickly (while CET-timezone ;) )

**Comment by LukBowen** [comment]
I can still do it; however, it will have to be later today. Currently working on a separate project at work.

**Comment by itinance** [comment]
Great and many thanks. No rush :)

**Comment by krzysztof-miemiec** [comment]
Hey, I just added a PR based on @jrichardlai's work. I hope we'll finally be able to work with content URI's on Android with no trouble! 🙂

**Comment by EyalSi** [comment]
I've just tested the latest version (2.9.7) and it's working perfectly! THANKS!

**Comment by smithaitufe** [comment]
It is not working for me.
I installed this package today hoping it will help me get the absolute file path but it is not working
```js
05-19 12:57:18.639  6494  7163 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
05-19 12:57:18.639  6494  7163 W ReactNativeJS: Error: File does not exist
```

**Comment by kushalsharma12** [comment]
content://com.android.providers.media.documents/document/image%3A400331
I got this when I uploaded an uri from my phone to firebase firestore ... any idea how to get the image from it?

**Comment by AliAzaz** [comment]
@kushalsharma12 have u got any solution for it?

**Comment by kushalsharma12** [comment]
@AliAzaz nope

**Comment by Usamaliaquat123** [comment]
any solution .... guys

**Comment by Merkost** [comment]
need a solution!

**Comment by hareesh7777** [comment]
> Hey @itinance, I just added a PR based on @jrichardlai's work. I hope we'll finally be able to work with content URI's on Android with no trouble! 🙂

i'm getting same error File does not exist
