### ISSUE TITLE
copyAssetsVideoIOS is not a function

### ISSUE THREAD

**Issue by sampurcell93** [itinance/react-native-fs#353]
Hi - I noticed this function the the Readme, but it doesn't seem to be included in the fs interface when I install. I just ran a fresh install of fs-latest.

Thanks!

**Comment by sampurcell93** [comment]
Ah, I see it only just landed in master. Any timetable on a stable release?

**Comment by itinance** [comment]
Hi! In upcoming days :)

**Comment by itinance** [comment]
pls find v2.8.1 on npm now.
