### ISSUE TITLE
how to rename a file?

### ISSUE THREAD

**Issue by huanghaodong** [itinance/react-native-fs#356]

**Comment by itinance** [comment]
Use [moveFile()](https://github.com/itinance/react-native-fs#movefilefilepath-string-destpath-string-promisevoid) for that. But pay attention that the "destPath"-Parameter not only contains the new filename but also the whole path.

**Comment by virenradadiya** [comment]
Hi there,

I'm experiencing the same issue with version "^4.2.1" of the npm library. Has anyone found a solution for this problem?

Thanks in advance for any assistance you can provide.

**Comment by torver213** [comment]
moveFile() or copyFile(), which one is better?
