### ISSUE TITLE
When the file is written, an error is thrown if the directory does not exist？

### ISSUE THREAD

**Issue by baijunjie** [itinance/react-native-fs#366]
```js
RNFS.writeFile(RNFS. DocumentDirectoryPath + '/data/myFile');
```
There is an error indicating that there is no "data" directory
So how do I create a "data" directory?

**Comment by itinance** [comment]
use RNFS.mkdir() as stated in the README.

**Comment by ManishAhire** [comment]
@itinance , How could I store data into newly created folder?
