### ISSUE TITLE
How to catch download errors?

### ISSUE THREAD

**Issue by crysfel** [itinance/react-native-fs#376]
Hi folks! Thank you so much for such a great job. Im having an issue where I don't know how to catch the failure when downloading a file.

For example, if the user lost network, how can I catch that? What I want is to show an alert message to the user, hide the download percentage message that I'm showing and delete the uncomplete download.

I have the following code, but it never runs the `catch`:
```
const result = FS.downloadFile({
      fromUrl: url,                   // URL to download file from
      toFile: `${CACHE_DIR}/${name}`, // Local filesystem path to save the file to
      background: false,        
      progressDivider: steps,
      begin: onBegin,
      progress: onProgress,
      readTimeout: 2 * MIN,
      connectionTimeout: 30 * SEC,
    });

    return result.promise
      .then(() => {
        this.index[name] = {
          name,
          path: `${CACHE_DIR}/${name}`,
          size: 0,
        };

        return this.index[name];
      })
      .catch((error) => {
        console.log('error!', error);   // <-- This code never runs :(

        // Show and alert message to the user...

       // Hide downloading message

       // Delete incomplete download file
     });
```

Thank you so much for your help.

**Comment by SrdjanCosicPrica** [comment]
I had this problem as well. It turns out that if the server returns a bad response I.E 400 then the code from the promise will still be resolved.

Meaning your code `.then()` will execute. I don't know why this is but I have come up with a workaround.

The promise resolves with this type of data 
```
{
    jobId: 1, 
    statusCode: 400
}
```
So in your `.then()` you could do
```
.then(response => {
    if (response.statusCode !== 200) { // Or something else, basically a check for failed responses
        throw response;
    }
}
```
This will make your `.catch()` execute.

**Comment by crysfel** [comment]
If I remember correctly... at the end I found out this only happens on the simulator, once you run the code in the actual device, disconnect from the network while downloading the file, it works fine, it will execute the catch successfully.

**Comment by unigeniee** [comment]
How about during download. For example: 50% completion, then internet gets corrupted. I cannot catch it

**Comment by n0umankhan** [comment]
strange catch or even then both did not trigger for my case. tested on simulator and in real device :(
