### ISSUE TITLE
How to create a folder in Camera Roll. I don't have permission to save image in the folder "asset" with mkdir

### ISSUE THREAD

**Issue by SvetoslavSlavov** [itinance/react-native-fs#394]
```
RNFS.mkdir('assets-library://asset/folder', {
                NSURLIsExcludedFromBackupKey: true
            }).then(() => {
                console.log("mkdir");
            });
```
![simulator screen shot - iphone 6 - 2017-11-28 at 16 39 03](https://user-images.githubusercontent.com/16868443/33325422-e18b7000-d45a-11e7-9c84-7e4ac0fa558f.png)

**Comment by itinance** [comment]
You can't create folders in iOS-Camera-Roll with the POSIX-style. There are special native methods necessary to create albums. 

But thanks for the hint! I guess we should add this feature to the library!

**Comment by lyseiha** [comment]
+1
