### ISSUE TITLE
Error: The file “.DS_Store” couldn’t be opened.

### ISSUE THREAD

**Issue by finferflu** [itinance/react-native-fs#402]
I've stumbled on this issue where I get the following error when I'm listing a folder (using the `readDir()` method) that contains a `.DS_Store` file:

```
Error: The file “.DS_Store” couldn’t be opened.
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:307)
    at MessageQueue.js:120
    at MessageQueue.__guard (MessageQueue.js:231)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:119)
    at debuggerWorker.js:72
```

Is there any way to prevent this error while using `RNFS.readDir(`)?

Thank you.

**Comment by itinance** [comment]
Read about DS_Store-Files: https://en.wikipedia.org/wiki/.DS_Store
Wouldnt happen on real device.

**Comment by finferflu** [comment]
Ah, thanks for clearing that up for me. Much appreciated!

**Comment by itinance** [comment]
Many thanx for your feedback!
