### ISSUE TITLE
Read image from assets-library

### ISSUE THREAD

**Issue by RobertoP2012** [itinance/react-native-fs#410]
I have an uri like this:

assets-library://asset/asset.JPG?id=ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED&ext=JPG

I try: 

 RNFS.readFile(image.node.image.uri).then(image => {
            console.log(image);
        });

Thanks

**Comment by itinance** [comment]
Use copyAssetsFileIOS()
Look at the Readme how to use it

Via IPhone...

**Comment by itinance** [comment]
`assets-library://` uses another API to read data from its files. 

Therefor i added this method copyAssetsFileIOS():

https://github.com/itinance/react-native-fs#copyassetsfileiosimageuri-string-destpath-string-width-number-height-number-scale--number--10-compression--number--10-resizemode--string--contain--promisestring
