### ISSUE TITLE
Android - Hash method still suffers from fix done for other on PR #395

### ISSUE THREAD

**Issue by castro13** [itinance/react-native-fs#418]
While trying to use the 'hash' method on Android, I was getting the same error that the PR #395 fixed.
I did a local fix to have ti working.

Is there any possibility of fixing the hash method?
Below is my fix.

      if (!algorithms.containsKey(algorithm)) throw new Exception("Invalid hash algorithm");

      // File file = new File(filepath);

      // if (file.isDirectory()) {
      //   rejectFileIsDirectory(promise);
      //   return;
      // }

      // if (!file.exists()) {
      //   rejectFileNotFound(promise, filepath);
      //   return;
      // }

      MessageDigest md = MessageDigest.getInstance(algorithms.get(algorithm));

      // FileInputStream inputStream = new FileInputStream(filepath);
      // byte[] buffer = new byte[(int) file.length()];

      InputStream inputStream = getInputStream(filepath);
      byte[] buffer = new byte[1024];

**Comment by andrewkvavlewhite** [comment]
I use this package only for the file hash function. I made a fork temporarily with the above fix if anyone else only cares about the hash function. https://github.com/andrewkvavlewhite/react-native-fs

**Comment by itinance** [comment]
I wonder why nobody send a PR with this fix? 
I have changed now the buffer creation to a fix buffer size of 10 KB in the hash-function. 
Please find the fix in latest release of v2.9.10

**Comment by tong233** [comment]
Thanks. it is working
