### ISSUE TITLE
Works on simulator but not physical device

### ISSUE THREAD

**Issue by lelong88** [itinance/react-native-fs#419]
Other users tried the app in TestFlight and it didn't work.

**Comment by itinance** [comment]
How shall we help you with this little kind of information? What have you done? Show at least some lines of code. I can tell you that i have a bunch of Apps in the AppStore and also PlayStore dealing with heavy file-system operations powered by react-native-fs.

If you really want our help, help us that we can help you!

**Comment by lelong88** [comment]
I only meant to give a small flag to those who are considering different options for storage. My test code is very small so this might be an issue with current iOS version (11.2.1). If someone needs specific capability to react-native-fs, I’m sure they’ll use it anyway. I used AsyncStorage after and it seems to be okay for now.

If it’s just my mistake, my apology. Please feel free to close if it’s not appropriate.

________________________________
