### ISSUE TITLE
Cannot read property 'download' of undefined

### ISSUE THREAD

**Issue by radjivC** [itinance/react-native-fs#427]
this is the line which is broken

```var _download = promisify(RNFileDownload.download)```

Any idea?

**Comment by kanalasumant** [comment]
what seems to be the error @radjivC ?

**Comment by itinance** [comment]
Apparent your variable `RNFileDownload` is unassigned. Look for your `import`-statement.
I will close due to inactivity. Pls feel free to reopen if your issue still persist. You should provide your code then including how you're importing RNFS.
