### ISSUE TITLE
Hash file, update file, run Hash again shows the same hash on Android

### ISSUE THREAD

**Issue by tlloydukdev** [itinance/react-native-fs#444]
Hi all

Got a strange one here, everything works as expected with iOS but on Android, it doesn't appear to be updating the file even though the new file is being used. The file in question is a SQLlite .db file. The process is:

0) File is stored in /data/user/0/com.myapp.app/files/
1) Check hash of existing db using hash() - returns `7cebdb1a90dd4fa290f8a63d569c5b6e`
2) Check hash in file on remote URL using downloadFile() - returns `a502c4d199399019b88f02b2b88bfd59`
3) If different, download new file using downloadFile() to a different location
4) Delete original file
5) Move new file over old file using moveFile()
6) Take new hash() - hash is correctly updated - returns `a502c4d199399019b88f02b2b88bfd59`
7) Reload app, step 1 shows hash of the old file - `7cebdb1a90dd4fa290f8a63d569c5b6e` - as if steps 3-5 didn't happen

What is strange is that the newly download file (SQLite db) is the correct one the app is using. It's as if Android is copying the downloaded file somewhere else, so that it's in a different path to where I expect in step 1. Unfortunately Android Device Monitor isn't working so I can't explore the FS, but trying to fix that in case it gives a clue.

Code looks like this for steps 3-6:

```
console.log("Downloading...");
            fs.downloadFile({
                fromUrl: 'https://remote.domain.com/database.db',
                toFile: fs.DocumentDirectoryPath + '/database_temp.db',
                progress: (data) => {
                    const percentage = (((100 * data.bytesWritten) / data.contentLength) / 100) | 0;
                    dispatch({ type: DOWNLOAD_PROGRESS, payload: percentage });
                }
            })
            .promise.then((res) => {
                console.log("Downloaded...");
                fs.exists(fs.DocumentDirectoryPath + '/database_temp.db').then((exists) => {
                    console.log("Exists:" + exists); // outputs true
                    if(exists) {
                        fs.unlink(fs.DocumentDirectoryPath + '/database.db').finally(() => {
                            fs.moveFile(fs.DocumentDirectoryPath + '/database_temp.db', fs.DocumentDirectoryPath + '/database.db').then(() => {
                                dispatch({ 
                                    type: DOWNLOAD_DB
                                }); 
                                fs.hash(fs.DocumentDirectoryPath + '/database.db', 'md5').then((hash) => {
                                    console.log('[!] Local hash is now ' + hash + ' for ' + fs.DocumentDirectoryPath + '/database.db');
                                });
                                Alert.alert(
                                    'Success',
                                    'Database successfully downloaded',
                                    [
                                    {text: 'OK', onPress: () => Actions.reset('main') },
                                    ],
                                    { cancelable: false }
                                );
                                                           
                            })
                            .catch((err) => {
                                dispatch({ type: DOWNLOAD_FAILED });
                                Alert.alert('Error', err.message, [ { text: 'OK' } ], { cancelable: false });
                            });
                        });                        
                        
                    } else {
                        dispatch({ type: DOWNLOAD_FAILED });
                        Alert.alert('Error', 'Database could not be found after download.', [ { text: 'OK' } ], { cancelable: false });
                    }
                });                
            })
            .catch((error) => {
                dispatch({ type: DOWNLOAD_FAILED });
                Alert.alert('Error', error.message, [ { text: 'OK' } ], { cancelable: false });
            })
        }
```

The above executes as expected and without error .... !!

Thanks to anyone for suggestions

Tim

**Comment by tlloydukdev** [comment]
I managed to get access to the file system via the emulator and it seems that DownloadFile is putting the files in `/data/data/com.myapp.app/files/` - whereas DocumentDirectoryPath returns  `/data/user/0/com.myapp.app/files/`

Any ideas how to get the right path ?

**Comment by itinance** [comment]
Actually `downloadFile` should put the file where you tell it to put with the toFile-parameter. Works here on all projects and with all devices this way as documented in Readme.  I bet there must be another thing causing your issue.

**Comment by tlloydukdev** [comment]
You are right... I believe this is my issue https://stackoverflow.com/questions/28708149/android-md5-checksum-of-sqlite-db-changes-after-copying

It seems that when you open the SQLite db on Android it adds a table, thus changing the MD5 of the file.

**Comment by itinance** [comment]
Glad you've found it out!
