### ISSUE TITLE
File exists...except it doesn't

### ISSUE THREAD

**Issue by timscott** [itinance/react-native-fs#452]
The following code:

```js
RNFS.exists(path).then(exists => {
  if (exists) {
    RNFS.readFileAssets(path, 'base64').then(file => {
      console.log(file);
    }).catch(err => {
      console.log(err);
    });
  }
});
```

Outputs this:
```
"ENOENT: no such file or directory, open '/data/user/0/com.mycompany.myapp.debug/files/my_file.pdf'"
```

The folder path of `/data/user/0/com.mycompany.myapp.debug/files/` is taken from `RNFS.DocumentDirectoryPath`.

The file was previously written with this code:

```js
// target is "/data/user/0/com.mycompany.myapp.debug/files/my_file.pdf"
RNFS.exists(target).then(exists => {
  if (!exists) {
    RNFS.readFileAssets(source, 'base64').then(file => {
      RNFS.writeFile(target, file, 'base64').then(() => {
        resolve();
      });
    });
  } else {
    resolve();
  }
});
```

I have an old Android (4.4) device that I test on. On that device everything works fine. A user who is on v7 got the error, and I am able to replicate it on a Genymotion virtual.

**Comment by timscott** [comment]
Never mind. Need to change `readFileAssets` to `readFile`.

**Comment by emannick** [comment]
RNFS.readFileAssets is not reading the csv file which is on this path '/android/app/src/main/assets/myFile.csv'
