### ISSUE TITLE
Download into DocumentDirectoryPath For IOS

### ISSUE THREAD

**Issue by kanalasumant** [itinance/react-native-fs#456]
How does one get files into DocumentDirectoryPath on IOS from Drive or Dropbox or Mail. On android, it' pretty straightforward and it just works or I can hardcode the path. I'm trying to display files from the DocumentDirectoryPath but I need files in there to get what I want. How do I do that. Any suggestions on this is appreciated.

Basically my question is, is there a way to access any file downlaoded from say, drive or dropbox with react-native.

**Comment by itinance** [comment]
Please provide us more information.

**Comment by kanalasumant** [comment]
Ah sorry about that, I forgot a '/' at the end like so:
```${RNFS.DocumentDirectoryPath}/```
