### ISSUE TITLE
'React/RCTBridgeModule.h' file not found - expokit / pods - iOS

### ISSUE THREAD

**Issue by alanlanglois** [itinance/react-native-fs#479]
I've linked the lib manually but I get this error:
My project is an expo (SDK 25) detached project, including react-native-iap.
It compiles fine when not linking react-native-fs

RNFSManager.h:9:9: 'React/RCTBridgeModule.h' file not found

When looking at another lib I've included (react-native-iap)
they use a conditional import for RCTBridgeModule : 
```
#if __has_include("RCTBridgeModule.h")
#import "RCTBridgeModule.h"
#else
#import <React/RCTBridgeModule.h>
#endif
```

When I try to add it to RFSManager.h
I got an error a little further in the RCTBirdgeModule itself:
`RCTBridgeModule.h:12:9: 'React/RCTDefines.h' file not found`

I was able to make it work on Android but not on iOS. I'm pretty new to the react native / cocoapod / xcode ecosystem maybe I'm missing something obvious?

**Comment by alanlanglois** [comment]
I managed to add the lib doing it:

- Removing the iOS folder of my project
- Re-detaching the app `exp detach`
- adding the lib in the fresh podfile: `pod 'RNFS', :path => '../node_modules/react-native-fs'`
- running `pod install`

I guess I should have tried it at the first place whereas trying to add it manually :)

**Comment by ScreamZ** [comment]
@alanlanglois What about react 0.11 that get installed, I see this fucking issues many times… We could make an reference in pods but even…
