### ISSUE TITLE
Read file from assets folder

### ISSUE THREAD

**Issue by EEimer** [itinance/react-native-fs#482]
Hey guys I just dont get it.

I want to share a pdf via share, this lib needs the pdf as base64, so I want to use this lib to provide the base64 string.

In my project it got folder like src or assets, so I just want to read the file from the react-native project path.

Example:
assets/sample.pdf
or src/component/sample.pdf

Anyone who can help me out with that?
Wrong library? 

Thanks in advance! 
```
  RNFS.readFile(`assets/sample.pdf`, 'base64').then((pdf) => {
      Share.open({
        url: `data:application/pdf;base64,${pdf}`,
        type: 'application/pdf'
      })
    });
```

**Comment by EEimer** [comment]
So still no idea.
I just converted the pdf to base64 once and stored it as json string. 
Works... maybe even better cause it just has to be converted once... 
If anyone finds the answer -> I would still be interested in it :)

**Comment by Stophface** [comment]
@EEimer Did you find a solution to this? Where must the file be saved in order to be accessible by this library?
