### ISSUE TITLE
incompatible with react native version 0.55?

### ISSUE THREAD

**Issue by Yinetsrl** [itinance/react-native-fs#484]
after install package and linked, when run-ios show error Cannot reacd property RNFSFileTypeRegular of undefined

**Comment by aaronleo28** [comment]
I get the same error on React Native version 0.53.3

**Comment by Yinetsrl** [comment]
hi
i resolved with manual link

aaronleo28 <notifications@github.com> 于 2018年4月30日周一 下午10:34写道：
