### ISSUE TITLE
uploadFiles leaks memory

### ISSUE THREAD

**Issue by ainth** [itinance/react-native-fs#499]
In `RNFSManager.m` in `uploadFiles` the new upload job is added to the `self.uploaders` dictionary. Jobs are never cleaned up and when uploading a large number of large files this will eventually crash the device (as in our case) as it seems the body of the request is retained.

I've confirmed this in xcode's instruments where I see `NSMutableData` objects being retained that are created from uploadFiles that are persisted and never get cleaned up.

**Comment by itinance** [comment]
Fixed by https://github.com/itinance/react-native-fs/pull/502
