### ISSUE TITLE
downloadFile returns 206 statusCode

### ISSUE THREAD

**Issue by kesha-antonov** [itinance/react-native-fs#512]
Hello!

I'm downloading mp3 files. For first one it returns 206 http statusCode. For others - 200. I need it all to be 200.
How to fix it?

**Comment by itinance** [comment]
Statuscode will always be received by the server. So you need to fix the server where you want to download files from. I‘m going to close this with mentioned reasons.

Maybe this helps: https://httpstatuses.com/206

**Comment by kesha-antonov** [comment]
I added ```"If-None-Match": ''``` to headers and now it's working. And returns status 200.
