### ISSUE TITLE
Can we use react-native-fs with Visual Studio Code on Windows?

### ISSUE THREAD

**Issue by Zerg00s** [itinance/react-native-fs#514]
Can someone, please explain if it's possible to use react-native-fs with Visual Studio Code + Windows? I've already spend more than 8 hours in two days and for the life of me, I can't figure it out. I've seen dozens examples with MacOs or XCode, but I'm not using either of these.

**Details:**
- I'm only starting with the react-native development.
- We are using an Expo app.
- Created an app using create-react-app-native.
react-native link react-native-fs does not seem to do anything:
_> react-native link react-native-fs_
_Scanning folders for symlinks in D:\Delete\o365app\node_modules (65ms)_

`require('react-native').NativeModules` contains an empty {} object
`RNFSManager` is undefined
![image](https://user-images.githubusercontent.com/2797648/42121023-a87bd476-7bf3-11e8-8b0d-c696eebd2535.png)

![image 2](https://user-images.githubusercontent.com/2797648/42121034-045ee6b6-7bf4-11e8-9d3b-620088755643.png)

**Comment by Zerg00s** [comment]
Sad news for those using Windows and react-native.

We cannot develop iOS apps using Windows. I mean none of the native modules are available when using Windows. Basically, you can toy around a little bit on Windows, but you can't develop any real apps.

When you eject react-native app using `yarn run` --> `eject` there is no way to eject the app for iOS.
This is what I get when ejecting on Windows: 

`Skipping iOS because you are not running macOS.`

**Comment by ScreamZ** [comment]
iOS development unavailable on anything else than MacOS.

Expo app doesn't support native module without ejection.

have fun ^^ (It's hard too with windows, dependencies are not simple as on unix based system and Line ending chars are pain)

**Comment by leoek** [comment]
@Zerg00s You can use react-native-fs in a react-native-windows app. However it does not work with expo.
