### ISSUE TITLE
No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

### ISSUE THREAD

**Issue by banli17** [itinance/react-native-fs#517]
a new project rn0.56，just install react-native-fs。when run react-native run-android ,error follow

```
node_modules/react-native-fs/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
```

**Comment by banli17** [comment]
i found it ，sdk version  issue。

**Comment by RodolfoSilva** [comment]
@banli17 How did you fix it? Share please, I'm having the same problem.

**Comment by RodolfoSilva** [comment]
Solution: https://github.com/itinance/react-native-fs/issues/507#issuecomment-403198880 and #519

**Comment by The-Code-Monkey** [comment]
Update your version as the lastest pr that I made was merged and it fixed it
