### ISSUE TITLE
please tag releases in the repository

### ISSUE THREAD

**Issue by mmerickel** [itinance/react-native-fs#538]
Can the project maintainers please start consistently tagging the releases in the repository? There are tags missing in the repo all over the place and it makes it extremely difficult to figure out what changed. For example the latest tag is 2.11 and npm has 2.11.15. We were on 2.9.7 at one point (which also has no tag) and the release notes have not been detailed enough to accurately show what has changed in the codebase. Tags are critical for deciding when to safely upgrade.

**Comment by itinance** [comment]
Hi @mmerickel, thanx for reaching out! I think the only gap you were stumpled into was the 2.9.7 right? If i remember correctly, 2.9.7. was only a short sequenze of seconds the most recent on NPM and i needed to make a new release then on 2.9.9, which is covered in the release-section.

For every minor version change there is a section in the README covering PRs and what has changed. Anything else that i can do? Something to suggest?

**Comment by mmerickel** [comment]
@itinance I'd expect to see every bugfix release tagged, even if you're only doing release notes for major/minor. Is there something non-obvious about the release process that would explain why 2.11 is the tag for the 2.11.15? Similarly 2.10 is actually 2.10.14. This pattern is non-standard across all of the open source projects I follow and I'd expect to see a tag for 2.11.15 specifically.

**Comment by itinance** [comment]
Yes, you're right. The last 2 releases have uncomplete tags against to those before. I'm use a shell script for this stuff and will check it. Must be a bug in my deployment tool. Thanks for pointing out!
Therefor i am going to close this issue. Next release will have complete tags again.

**Comment by mmerickel** [comment]
Thanks for the quick responses @itinance!

**Comment by itinance** [comment]
You're welcome!
