### ISSUE TITLE
RNFS.stat doesn't work on directories on Android

### ISSUE THREAD

**Issue by searene** [itinance/react-native-fs#540]
I created a normal file and a directory in `RNFS.ExternalStorageDirectoryPath` on Android, and applied `stat` on them respectively.

```javascript
const statOfFile = await RNFS.stat(RNFS.ExternalStorageDirectoryPath + "/ThisIsAFile");
const statOfDirectory = await RNFS.stat(RNFS.ExternalStorageDirectoryPath + "/ThisIsADirectory");
````

The first line worked, but the second line threw an exception:

```
08-16 09:05:28.747  8254  8286 W ReactNativeJS: Error: EISDIR: illegal operation on a directory, read '/storage/emulated/0/ThisIsADirectory'
```

It seemed to me that I couldn't use `stat` on directories on Android.

Version:
* Android: using the android emulator shipped with Android Studio, version: 8.1
* react-native: 0.55.4
* react-native-fs: 2.11.15

**Comment by tomwir** [comment]
exacly same problem, and also moveFile got same error

**Comment by hejile** [comment]
A sample stacktrace from logcat:

W/System.err( 2875): com.rnfs.IORejectionException: EISDIR: illegal operation on a directory, read '/data/data/com.teach_elders_read/files/tasks'
W/System.err( 2875):    at com.rnfs.RNFSManager.getFileUri(RNFSManager.java:75)
W/System.err( 2875):    at com.rnfs.RNFSManager.getOriginalFilepath(RNFSManager.java:83)
W/System.err( 2875):    at com.rnfs.RNFSManager.stat(RNFSManager.java:535)

**Comment by NelGarbuzova** [comment]
+ 1

**Comment by ramanandapanda** [comment]
Guys, any work around I am not able to fix this issue?

**Comment by Weedoze** [comment]
Following the `RNFS.readDir` documentation it will return you an object 
```
type ReadDirItem = {
  ctime: date;     // The creation date of the file (iOS only)
  mtime: date;     // The last modified date of the file
  name: string;     // The name of the item
  path: string;     // The absolute path to the item
  size: string;     // Size in bytes
  isFile: () => boolean;        // Is the file just a file?
  isDirectory: () => boolean;   // Is the file a directory?
};
```
Thus you can use this method to find files and directories in a folder. You can check for the name of the file or directory to find a specific one
```
RNFS.readDir(RNFS.ExternalStorageDirectoryPath)
.then(results => {
        const files = results.filter(result => result.isFile());
        const folders = results.filter(result => result.isFolder());
	const myFile = files.find(file => file.name === "ThisIsAFile");
        const myFolder = folders.find(folder => folder.name === "ThisIsAFolder");
})
.catch(err => {
	console.log(err);
});

```

**Comment by ramanandapanda** [comment]
I have tried in following way
```js
RNFS.exists(`${RNFS.CachesDirectoryPath}/TEST`).then((isExist)=>{
            if(isExist){
              RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
            }else{
              RNFS.mkdir(`${RNFS.CachesDirectoryPath}/TEST`,).then((data)=>{
                RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
              })
            }
          })
```
getting the same error 
EISDIR: illegal operation on a directory, read '/storage/emulated/0/Pictures/'

**Comment by hejile** [comment]
> Guys, any work around I am not able to fix this issue?

you can try my fork https://github.com/hejile/react-native-fs , which fixes 3 bugs. BTW, this project is really buggy.

**Comment by itinance** [comment]
@hejile a PR with fixes is always appreciated :)

**Comment by yanivtabibi** [comment]
@hejile Please review my PR for this fix
Thanks

**Comment by thisisirfan** [comment]
> I have tried in following way
> 
> ```js
> RNFS.exists(`${RNFS.CachesDirectoryPath}/TEST`).then((isExist)=>{
>             if(isExist){
>               RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
>             }else{
>               RNFS.mkdir(`${RNFS.CachesDirectoryPath}/TEST`,).then((data)=>{
>                 RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
>               })
>             }
>           })
> ```
> 
> getting the same error
> EISDIR: illegal operation on a directory, read '/storage/emulated/0/Pictures/'

Hi, Did you found any solution for this error ?

**Comment by NeliHarbuzava** [comment]
> > I have tried in following way
> > ```js
> > RNFS.exists(`${RNFS.CachesDirectoryPath}/TEST`).then((isExist)=>{
> >             if(isExist){
> >               RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> >             }else{
> >               RNFS.mkdir(`${RNFS.CachesDirectoryPath}/TEST`,).then((data)=>{
> >                 RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> >               })
> >             }
> >           })
> > ```
> > 
> > 
> > getting the same error
> > EISDIR: illegal operation on a directory, read '/storage/emulated/0/Pictures/'
> 
> Hi, Did you found any solution for this error ?

It seems you have no rights to read the directory "/storage/emulated/0/Pictures/" or it does not exists I think.

**Comment by thisisirfan** [comment]
@NeliHarbuzava  But i have already allowed user for External Read And Write Permission and i'm able to get all files inside these directories but not able to copy them

**Comment by thisisirfan** [comment]
> > > I have tried in following way
> > > ```js
> > > RNFS.exists(`${RNFS.CachesDirectoryPath}/TEST`).then((isExist)=>{
> > >             if(isExist){
> > >               RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> > >             }else{
> > >               RNFS.mkdir(`${RNFS.CachesDirectoryPath}/TEST`,).then((data)=>{
> > >                 RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> > >               })
> > >             }
> > >           })
> > > ```
> > > 
> > > 
> > > getting the same error
> > > EISDIR: illegal operation on a directory, read '/storage/emulated/0/Pictures/'
> > 
> > 
> > Hi, Did you found any solution for this error ?
> 
> It seems you have no rights to read the directory "/storage/emulated/0/Pictures/" or it does not exists I think.

BTW Am i request correct permission ?
`PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE` & 'PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE'

**Comment by thisisirfan** [comment]
> > > > I have tried in following way
> > > > ```js
> > > > RNFS.exists(`${RNFS.CachesDirectoryPath}/TEST`).then((isExist)=>{
> > > >             if(isExist){
> > > >               RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> > > >             }else{
> > > >               RNFS.mkdir(`${RNFS.CachesDirectoryPath}/TEST`,).then((data)=>{
> > > >                 RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> > > >               })
> > > >             }
> > > >           })
> > > > ```
> > > > 
> > > > 
> > > > getting the same error
> > > > EISDIR: illegal operation on a directory, read '/storage/emulated/0/Pictures/'
> > > 
> > > 
> > > Hi, Did you found any solution for this error ?
> > 
> > 
> > It seems you have no rights to read the directory "/storage/emulated/0/Pictures/" or it does not exists I think.
> 
> BTW Am i request correct permission ?
> `PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE` & `PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE`

@NeliHarbuzava  I managed to fixed it, it was silly mistake. Thanks or help though
[https://github.com/itinance/react-native-fs/issues/792](url)

**Comment by stepupithubapp** [comment]
> > > > > I have tried in following way
> > > > > ```js
> > > > > RNFS.exists(`${RNFS.CachesDirectoryPath}/TEST`).then((isExist)=>{
> > > > >             if(isExist){
> > > > >               RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> > > > >             }else{
> > > > >               RNFS.mkdir(`${RNFS.CachesDirectoryPath}/TEST`,).then((data)=>{
> > > > >                 RNFS.moveFile("/storage/emulated/0/Pictures/IMG_20181024_181202.jpg",`${RNFS.CachesDirectoryPath}/TEST`).then(console.log).catch(console.error)
> > > > >               })
> > > > >             }
> > > > >           })
> > > > > ```
> > > > > 
> > > > > 
> > > > > getting the same error
> > > > > EISDIR: illegal operation on a directory, read '/storage/emulated/0/Pictures/'
> > > > 
> > > > 
> > > > Hi, Did you found any solution for this error ?
> > > 
> > > 
> > > It seems you have no rights to read the directory "/storage/emulated/0/Pictures/" or it does not exists I think.
> > 
> > 
> > BTW Am i request correct permission ?
> > `PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE` & `PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE`
> 
> @NeliHarbuzava I managed to fixed it, it was silly mistake. Thanks or help though
> [https://github.com/itinance/react-native-fs/issues/792](url)
hey ??? how to copy file i'm etting error of EISDIR: illegal operation on a directory, read '/storage/emulated/0/Pictures'
