### ISSUE TITLE
Access the file created by react-native-fs by native ios Objective c code

### ISSUE THREAD

**Issue by yli18** [itinance/react-native-fs#554]
It's more like a question rather than an issue.
I created a file using react-native-fs and want to read it at native module using objective c.

In my case the file path is:
/var/mobile/Containers/Data/Application/8BDBB76C-A803-4F75-88A7-77DFFBCF8388/Documents/test.md

[[NSFileManager defaultManager] fileExistsAtPath:filepath]
I tried to access it from ios native module with this file path but not succeed, even with "file://" prefix

What is the correct filePath format?

**Comment by maxkomarychev** [comment]
Are you reading file in the same session or after app restarts?
not sure this is the actual case but may be good to know that you should never store absolute paths for your files since they will be different every time you start the app: https://stackoverflow.com/a/27443165

**Comment by yli18** [comment]
You are right, never to store absolute paths. At the beginning I tried resource path like "file://" which seems not working either.
 
Right now I'm using a work around, instead of create a file with react-native-fs, i create it in native module. 

Thanks
