### ISSUE TITLE
Could not find method implementation

### ISSUE THREAD

**Issue by li-shuaishuai** [itinance/react-native-fs#570]
Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

What happened?

**Comment by hank121314** [comment]
What is your react-native version and react-native-fs version?

**Comment by itinance** [comment]
Any news on this? With latest release this issue should be fixed in favour of Gradle 3 support.

**Comment by VictorParraCant** [comment]
Hi, I just had the same problem with the `implementation 'com.facebook.react: react-native: +'`
**AVD: Nexus5X API28 - 8.1.0**
**react-native: 0.57.3,** 
** react-native-fs: ^2.12.0** 

The error in my shell is this:
`JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Task :app:compileDebugJavaWithJavac FAILED
/testapp/android/app/src/main/java/com/testapp/MainApplication.java:13: error: package com.rnfs does not exist
import com.rnfs.RNFSPackage;
               ^
/testapp/android/app/src/main/java/com/testapp/MainApplication.java:50: error: cannot find symbol
      new RNFSPackage()
          ^
  symbol:   class RNFSPackage
  location: class MainApplication
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
...`

To solve it I used: `react-native link react-native-fs` in addition to the manual configuration, and has created the `compile project(':react-native-fs')` in _build.gradle_

I also had to comment on the `@Override` of the _MainApplication_ file

Now it only shows a warning, but it works correctly.

**Comment by FibreFoX** [comment]
@li-shuaishuai you are using some outdated gradle/gradle-wrapper, using some more up2date version like `4.6` has this `implementation` dependency-configuration. No but of this lib!

**Comment by omarkhaled11** [comment]
gradle/gradle-wrapper is outdated as FibreFox mentioned, to update it do the following:
Update build tools in: /android/build.gradle to:
`classpath 'com.android.tools.build:gradle:3.0.1'`

Update gradle version in `/android/gradle/wrapper/gradle-wrapper.properties` to gradle-4.1-all.zip
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`

You might encounter another issue if you don't have `maven { url 'https://maven.google.com' }` listed at the top under buildscript > repositories in /android/build.gradle

also if it asks you to accept the licenses for Android new version, you can accept licenses from the terminal by running this command `SDK-LOCATION/tools/bin/sdkmanager --licenses`
