### ISSUE TITLE
android No such file or directory downloadFile

### ISSUE THREAD

**Issue by dora-ljh** [itinance/react-native-fs#582]
download = (uri) => {
    if (!uri) return null;
    return new Promise((resolve, reject) => {
      let timestamp = (new Date()).getTime();//获取当前时间错
      let random = String(((Math.random() * 1000000) | 0))//六位随机数
      let dirs = Platform.OS === 'ios' ? RNFS.LibraryDirectoryPath : RNFS.ExternalDirectoryPath; //外部文件，共享目录的绝对路径（仅限android）
      const downloadDest = `${dirs}/${timestamp + random}.mp4`;
      const formUrl = uri;
      const options = {
        fromUrl: formUrl,
        toFile: downloadDest,
        background: true,
        begin: (res) => {
          this.setState({text:""})
          console.log('begin', res);
          // console.log('contentLength:', res.contentLength / 1024 / 1024, 'M');
        },
        progress:(res)=>{
          let pro = res.bytesWritten / res.contentLength;
          this.setState({progress:pro});
          // console.log(pro)
        }
      };
      try {
        const ret = RNFS.downloadFile(options);
        ret.promise.then(res => {
          // console.log('success', res);
          // console.log('file://' + downloadDest)
          var promise = CameraRoll.saveToCameraRoll(downloadDest);
          promise.then((result) => {
            console.log('保存成功！地址如下：\n' + result);
            if(!result)return reject(new Error("保存失败"))
            resolve(res);
          }).catch((error) => {
            reject(new Error(error))
            console.log('保存失败！\n' + error);
          });

        }).catch(err => {
          reject(new Error(err))
        });
      } catch (e) {
        reject(new Error(e))
      }

    })

  }

Error: /storage/emulated/0/Android/data/com.nicaiapp/files/1542073571633176573.mp4 (No such file or directory)

It's okay to save video on ios
But this error occurred when I saved it on android. What's the reason

**Comment by Wish-ljh** [comment]
"react-native-fs": "^2.11.15"
