### ISSUE TITLE
[Question] Is it possible to move a folder from bundle to documents directory?

### ISSUE THREAD

**Issue by plrthink** [itinance/react-native-fs#59]
I want to move a folder from bundle directory to document directory, but when I implementing this using RNFS.move method, it throw an error which says “p72DF976CA7517E265BD17-1456993742” couldn’t be moved because you don’t have permission to access “Documents” on real device with cable plugged in. But I could move such a folder on simulator. Also I can download files to document folder on real device using another plugin, so I think I have that permission.

Any ideas?

**Comment by johanneslumpe** [comment]
Are you sure that on a device you are allowed to move files out of the bundle? I'd think that you would have to copy them.

**Comment by plrthink** [comment]
@johanneslumpe Actually I'm not sure about that on a real device, sorry for open an issue without enough investigation. So how can I achieve this or I couldn't do that by all means.

**Comment by johanneslumpe** [comment]
@plrthink We don't currently have a method to copy files. Do you want to open a PR?

**Comment by plrthink** [comment]
@johanneslumpe I would try this feature when I have time.

**Comment by superandrew213** [comment]
#127
