### ISSUE TITLE
Xcode build error: Redefinition of 'options' in RNFSManager.m

### ISSUE THREAD

**Issue by sergeysemko** [itinance/react-native-fs#602]
```
node_modules/react-native-fs/RNFSManager.m:820:26: redefinition of 'options'
  PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc]init];

```

**Comment by radeno** [comment]
This commit brings error https://github.com/itinance/react-native-fs/commit/8eed082b6003b2e5decd9441b39012b9c1e291d4 because duplicate options.

Hotfix for users with same error.
1. revert to 3.12
2. or remove from file `RNFSManager.m` lines 814 and 815, they are duplicated

**Comment by itinance** [comment]
Hotfix is out. Please update to 2.13.2
