### ISSUE TITLE
RNFS.downloadFile works but file size is greater than expected

### ISSUE THREAD

**Issue by shubham1164** [itinance/react-native-fs#613]
Using:
===== 
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-fs": "^2.13.3"

Issue: 
====
RNFS.downloadFile is working fine on both Android and IOS but I have noticed an increase in downloaded filesize by 15-20% . for example: I have downloaded the file having original size=**60923**B on the server. But the downloaded version size=**71997**B. Facing the issue on both the platform (android + IOS).

Is it normal or I am using doing wrong?

Code
====
```
    try {
      const downloadResult = await RNFS.downloadFile({
                             fromUrl: url,
                             toFile: toFile
                           }).promise;
      // verify by reading the file
      const statResult = await RNFS.stat(toFile);
      console.warn("afterDown: ", downloadResult, statResult);
    } catch(e){
      console.warn("err: ", e.message);
    }
```

**Comment by shubham1164** [comment]
Has anybody experience the similar behaviour?

**Comment by hnny09** [comment]
I have same problem，how to solve
