### ISSUE TITLE
Error: You don't have permission to save the file in the folder (iOs)

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [itinance/react-native-fs#619]
Works just fine on Android simulator and devices.

The error is thrown when I create a folder:

    export default class GalleryScreen extends React.Component {
        componentDidMount() {
            const dir = FileSystem.ExternalDirectoryPath + '/photos';
            this.ensureDirExist(dir).then(() => {
                ......<My code here>
            });
        };
    
        ensureDirExist = async (dir) => {
            const exists = await FileSystem.exists(dir);
            if (exists) {
                return exists;
            }
            await FileSystem.mkdir(dir);
        };
    }

Please help. Thank you.

**Comment by KonstantinKolodnitsky** [comment]
<img width="321" alt="screen shot 2019-01-19 at 10 05 15" src="https://user-images.githubusercontent.com/2089543/51417361-c0e72780-1bd1-11e9-98a6-4c9e202d720e.png">
One of the error in the stack

**Comment by KonstantinKolodnitsky** [comment]
Aha. ExternalDirectoryPath is for Android only!
Sorry. My fault.

**Comment by cihanbas** [comment]
Hi @KonstantinKolodnitsky  how did you fix it, can you help me 
`    this.root = [RNFS.ExternalStorageDirectoryPath, "Elci"].join("/");

    await Promise.all(Object.keys(FOLDERS).map(async (name) => {
      try {
        const path = [this.root, FOLDERS[name]].join("/");
        console.log("path", path)

        const exists = await RNFS.exists(path);
        console.log("exists", exists)

        if (!exists) {
          await RNFS.mkdir(path + "/");
        }
      } catch (e) {
        console.log(e);
      }
    }));`

**Comment by KonstantinKolodnitsky** [comment]
Hi, @cihanbas From docs:
`ExternalStorageDirectoryPath (String) The absolute path to the external storage, shared directory (android only)`

Android ONLY!
