### ISSUE TITLE
Download speed is too low

### ISSUE THREAD

**Issue by sinodko** [itinance/react-native-fs#629]
Hello. I would like to ask why the download speed (downloadFile function) is so low? While I was using rn-fetch-blob lib the download speed was so much better. I have progressDivider set on '2'

**Comment by Macromeda** [comment]
i disagree, the download progress is fine with me, i set the progressDivider to '5'
check the download progress on different networks.

**Comment by sinodko** [comment]
i have progressDivider set to '5' and 100mb files download is about 10 minute long... with rn-fetch-blob package the download speed was about 30 seconds for the same file on same internet network..
