### ISSUE TITLE
'YGValue.h' file not found

### ISSUE THREAD

**Issue by isaaclem** [itinance/react-native-fs#652]
When I upgraded my RN from `0.57.8` to `0.59.3`, I failed to build my ios using XCode with the error `YGValue.h file not found` under `Compile RNFSManager.m`, wondering if anyone facing the similar problem?

```js
"react": "16.8.3",
"react-native": "0.59.3",
"react-native-fs": "^2.13.3",
```

**Comment by edritech93** [comment]
same issue for me, any solution ?

**Comment by isaaclem** [comment]
@edritech93 : In my case, it was due to setup process, I've mixed between pods and manual installation, so what I did was, undo whatever statement I wrote in podfile and making sure I only follow manual installation way
