### ISSUE TITLE
Download doesn't timeout on IOS

### ISSUE THREAD

**Issue by wamry** [itinance/react-native-fs#656]
I checked using network link conditioner with 100% loss, even with turning off the wifi, the download doesn't fail.
I like the resumable feature, but what if i want it to fail after the timeout is exceeded ?

This is my downloadFileOptions object:
```
const downloadFileOptions = { 
	fromUrl,
	toFile,
	background: true,
	discretionary: true,
	cacheable: false,
	progressDivider: 5,
	readTimeout: 15000,
	connectionTimeout: 5000,
	progress: (data) => {
		myCallBackOnProgress(data);
	},
	resumable:() => {
		return false
	}
}
```

**Comment by a-koka** [comment]
It's a known issue that when iOS enables background downloading, it ignores the timeout errors. Just disable background downloading when timeouts are important.

@itinance Perhaps we should add this information to the documentation. I lost a half day trying to figure this out myself. Thank you!

**Comment by wamry** [comment]
tried it with "background: false", still wouldn't timeout on ios.

**Comment by a-koka** [comment]
Below is my code. Can you try with something similar? You have some extra props that may be getting in the way.

```
                RNFS.downloadFile({
                      fromUrl,
                      toFile,
                      progressDivider,
                      begin: res => {
                        contentLength = res.contentLength;
                        if (onBegin) onBegin(res);
                      },
                      progress: onProgress,
                      connectionTimeout: 1500,
                      readTimeout: 1500,
                      background: false
                 }).then().catch(err => // Get the timeout error here)
```

@itinance Forgot to mention earlier, the documentation should also say that the timeouts are in milliseconds. Thank you!
