### ISSUE TITLE
Unable to start background download [IOS]

### ISSUE THREAD

**Issue by Linoa65** [itinance/react-native-fs#666]
Hello !

I have some problem to download a file when the app is in background.
When I receive a notification, the callback is correctly called, but the thread is blocked unless I open the app, then the download can starts.
I want to be able to download my file during my app is in background to do something after that, but for now, it is impossible.

I added this on AppDelegate.m
```objectivec
// Required for background downloading
- (void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)())completionHandler
{
  [RNFSManager setCompletionHandlerForIdentifier:identifier completionHandler:completionHandler];
}
```

and this is a snippet of my callback :

```js
const rnfsResult = RNFS.downloadFile({
     fromUrl: myUrl,
     toFile: myFile,
     background: true,
     discretionary: true,
});

rnfsResult.promise.then(() => {
     RNFS.completeHandlerIOS(rnfsResult.jobId);
     // Processing something ..........
});
```

I follow instructions on README.md, but nothing to do, my background never start unless I open my app...

**Comment by Linoa65** [comment]
It seems there is incompatibles between this module and react-native-notifications. I change to now use react-native-push-notifications and it seems to works better and I'm able to start my download on each notification if I need it.

I close it, feel free to re-open if someone have problems !

Florient

**Comment by pvn** [comment]
I am facing the same issue.

I am using **"react-native-fs": "^2.16.6"**

```
// Required for background downloading
-(void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)())completionHandler
{
  [RNFSManager setCompletionHandlerForIdentifier:identifier completionHandler:completionHandler];
}
```
```
const downloadConfigOptions = {
        fromUrl: url,
        toFile: filePath,
        headers: header,
        background: true,
        readTimeout: 600 * 10000,
        connectionTimeout: 1000 * 10,
        discretionary: true,
        begin: downLoadBegin
      };
```
But when the app goes in background, download stops.

I even set the Background Modes as Background Fetch in the app project settings.
