### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by opoze** [itinance/react-native-fs#709]
RNFSManager.java
-import android.support.annotation.Nullable;
+import androidx.annotation.Nullable

... etc

**Comment by GregLovesCoding** [comment]
Same request

**Comment by gomdolkim** [comment]
Same request. I got this issue after upgrading react native with 0.59.9. I believe this PR merge to master soon. https://github.com/itinance/react-native-fs/pull/691/files

**Comment by itinance** [comment]
please install v2.14.0.
I am going to close this issue. Pls feel free to reopen it if this issue still persists
