### ISSUE TITLE
Cannot find file in the device after export file using the example 

### ISSUE THREAD

**Issue by Exeexe93** [itinance/react-native-fs#720]
Hi,

I could not find any excel file in xlsx format in my device after I press the export data button using the example in [react-native.js](https://github.com/SheetJS/js-xlsx/blob/master/demos/react/react-native.js). Although it shows that it is being exported to /data/user/0/com.test/files/sheetjsw.xlsx in the alert after pressing the button. 

Anyone can help with this issue? Thanks!

**Comment by allyyc-ndz** [comment]
Same issue here.Can't see the exported file in the ios devices.Anyone can help with this issue?

**Comment by allyyc-ndz** [comment]
The issue is fixed for me  by adding   <key>UIFileSharingEnabled</key>
  <string>YES</string>
  <key>LSSupportsOpeningDocumentsInPlace</key>
  <string>YES</string> in the plist
