### ISSUE TITLE
RNFS.uploadFiles only works for raw uploads not for multipart/form-data

### ISSUE THREAD

**Issue by rizshivalli** [itinance/react-native-fs#724]
I was trying to upload JSON files to the nodejs server which is usng multer as a middleware to receive files and the RNFS.uploadFiles only works for raw Multer and does not work for the multer which has a specific field eg(upload.single('files')

**RNFS Upload Code**

```
var file = [
                    {
                        name: newpath,
                        filename: newpath,
                        filepath: newpath,
                        filetype: 'json'
                    }
                ];


                var uploadBegin = (response) => {
                    var jobId = response.jobId;
                    console.log('UPLOAD HAS BEGUN! JobId: ' + jobId);
                };

                var uploadProgress = (response) => {
                    var percentage = Math.floor((response.totalBytesSent / response.totalBytesExpectedToSend) * 100);
                    console.log('UPLOAD IS ' + percentage + '% DONE!');
                };

                RNFS.uploadFiles({
                    toUrl: uploadUrl,
                    files: file,
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json',
                    },

                    begin: uploadBegin,
                    progress: uploadProgress
                }).promise.then((response) => {
                    if (response.statusCode == 200) {
                        console.log('FILES UPLOADED!'); 
                    } else {
                        console.log('SERVER ERROR');
                    }
                })
                    .catch((err) => {
                        if (err.description === "cancelled") {
                            // cancelled by user
                        }
                        console.log(err);
                    });

                // }
            })
            .catch((err) => {
                console.log(err.message);
            });

```

**multer code** 

```
var upload = multer({
    storage: storage,// fileFilter: fileFilter
});

router.post('/GetFiles', upload.single('files'), function (req, res) {


    if (req.file) {
        res.send({ "Status": true, "Msg": "File Uploaded Successfully" });      
    }
    else {      
        res.send({ "Status": false, "Msg": "Failed to upload the File", "body": req.body });
    }

})
```

and is giving error
`Error: ENOENT: no such file or directory, open 'http://192.168.1.15:3333/SurveyJsonFiles/GetFiles/'
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:80`

any Idea how to fix this?

**Comment by hank121314** [comment]
I think change 
`var file = [
                    {
                        name: newpath,
                        filename: newpath,
                        filepath: newpath,
                        filetype: 'json'
                    }
                ];
 `
into
`var file = [
                    {
                        name: 'files',
                        filename: newpath,
                        filepath: newpath,
                        filetype: 'json'
                    }
                ];

 `
should fix this issue.

**Comment by rizshivalli** [comment]
@hank121314 Thank you It is working now for multipart/form-data but only for small files when i try to upload files bigger than 1 MB it is showing socket closed error

`Error: Socket closed
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:80`

**Comment by hank121314** [comment]
Try to remove the filetype in var files. If it's still not working, please show me your repo! Thanks

**Comment by rizshivalli** [comment]
Hi @hank121314 Thank you for your answers, It seems the files were not getting uploaded completely because nodemon was restarting the node server every time the device was sending a new file

**Comment by kfayay** [comment]
@rizshivalli have you solved this problem. i have the same problem .files not getting uploaded with socket close

**Comment by rizshivalli** [comment]
@kfayay For me the problem was the API was storing the files on the same folder as the node js server so nodemon was restarting every time a change in a file or new file was being uploaded
since the server was restarting the socket closed error was showing so i have moved the uploads folder and the issue was resolved
