### ISSUE TITLE
Big file upload error for android  - 'Error: unexpected end of stream'

### ISSUE THREAD

**Issue by m-inan** [itinance/react-native-fs#766]
### Issue Description
I have no problem installing with `IOS`. The upload succeeds regardless of the file size. However, when I use the same installation method for android, small files are loaded, but **large files** are not. Just `Android` and **big mp3 file**. 

#### Code
```javascript
const { promise } = RNFS.downloadFile({
  fromUrl,
  toFile,
  progressDivider: 5,
  progress: res => console.log('progress', res),
  begin: res => console.log('begin', res)
})

try {
  await promise
  console.log('success')
} catch (error) {
  // Error: unexpected end of stream
  console.log(error)
} finally {
  console.log('final')
}
```
#### Error Output
```javascript
Error: unexpected end of stream
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at RNDebuggerWorker.js:2
```
#### Console Image
<img width="948" alt="Screen Shot 2019-09-26 at 20 05 24" src="https://user-images.githubusercontent.com/25525515/65709236-03360200-e099-11e9-8c04-54d9118a1548.png">

### Environment
* React Native FS version: ^2.13.3
* React Native version: ^0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - Device (Samsung Galaxy S10), Android 9, Debug - Release

**Comment by euroclydon37** [comment]
I'm getting this as well.

**Comment by euroclydon37** [comment]
The issue title isn't accurate, though. I'm having problems with _downloading_, as is the OP.

**Comment by euroclydon37** [comment]
This is the error I get. It's identical, as far as I can tell, to the error thrown in #596. But the problem there was a bad file path for _uploading_. This is happening when trying to _download_ a large file.

<img width="586" alt="Screen Shot 2019-10-29 at 9 03 55 AM" src="https://user-images.githubusercontent.com/9101935/67774267-0bcc8000-fa2b-11e9-8240-c49278ab6473.png">

**Comment by take-o20** [comment]
I had the same error.
But in my case, this was resolved by writing the big file at RNFS.CachesDirectoryPat, and upload file from that writed file path.

**Comment by minhna** [comment]
I had the same issue. My filepath was like `file:///storage/emulated/0/Android/data/com.potato/files/Pictures/cbfadf52-7fb1-4806-b3ed-8cb0bb498853.jpg`
I removed the `file://` and it works.

**Comment by ssshopyak** [comment]
> I had the same issue. My filepath was like `file:///storage/emulated/0/Android/data/com.potato/files/Pictures/cbfadf52-7fb1-4806-b3ed-8cb0bb498853.jpg` I removed the `file://` and it works.

you make my day big thanks<3
