### ISSUE TITLE
EISDIR: illegal operation on a directory, read while using copyFile method

### ISSUE THREAD

**Issue by thisisirfan** [itinance/react-native-fs#792]
I'm trying simple code to copy a file to another external folder using this code:
`
RNFS.copyFile(sourcePath, destinationPath)
.then(result => {
  console.log('file copied:', result);
})
.catch(err => {
  console.log('error: ', err.message, err.code);
});
`
and i have already granted Android.Permission for read and write in external directory but it's still returning this error:

`error:  EISDIR: illegal operation on a directory, read '/storage/emulated/0/' EISDIR`
here are the dependency:

`
"react": "16.9.0",
"react-native": "0.61.2",  
"react-native-fs": "^2.15.2"
`
Thanks for help in advance

**Comment by thisisirfan** [comment]
I have resolved this issue, It was silly mistake. I forgot to mention name of the file in destination path url:

`
let destinationPath = statusDirPath + '/' + this.props.media.name;
      RNFS.copyFile(sourcePath, destinationPath)
        .then(result => {
          console.log('file copied:', result);
        })
        .catch(err => {
          console.log(err);
        });
`

**Comment by mofengfs** [comment]
@thisisirfan 
I have a similar problem with you, but I don't think it is a file name problem, because I have named each file.
https://github.com/itinance/react-native-fs/issues/979#issue-804042154

**Comment by Yasir12598** [comment]
@codthing  Try this it works for me.
```
import {view, StyleSheet, PermissionsAndroid} from from 'react-native';

PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
    PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE);
```

**Comment by hb-webdev** [comment]
> I have resolved this issue, It was silly mistake. I forgot to mention name of the file in destination path url:
> 
> ```
> let destinationPath = statusDirPath +"/"+ this.props.media.name;
>       RNFS.copyFile(sourcePath, destinationPath)  
>         .then(result => {  
>           console.log('file copied:', result);
>         })
>         .catch(err => {
>           console.log(err);
>         });
> ```

So...does`copyFile` require the name of a File rather than a Folder?

In iOS, `copyFile` doesn't throw this error: I can copy a whole Folder to a new Folder name.

**Comment by hareesh7777** [comment]
> > I have resolved this issue, It was silly mistake. I forgot to mention name of the file in destination path url:
> > ```
> > let destinationPath = statusDirPath +"/"+ this.props.media.name;
> >       RNFS.copyFile(sourcePath, destinationPath)  
> >         .then(result => {  
> >           console.log('file copied:', result);
> >         })
> >         .catch(err => {
> >           console.log(err);
> >         });
> > ```
> 
> So...on Android, does`copyFile` require the name of a File rather than a Folder?
> 
> In iOS, `copyFile` doesn't throw this error: I can copy a whole Folder to a new Folder name.
> 
> EDIT: Well. I ended up using `readDir()` on the parent directory, then `.map` to iterate over the `readDir()` result to recreate each subfolder in the new parent directory, then `copyFile` to move each file to the respective new subfolder. -_- Everything is so much easier on iOS--not as many bugs/annoyances

i'm new here can you give me the sample code for this, in ios how to download file with copyFile

**Comment by kunleathaiwo** [comment]
I've ran into similar problem while deploying to eas ios. Please i need help

Error: [ios.xcodeproj]: withIosXcodeprojBaseMod: EISDIR: illegal operation on a directory, copyfile '/Users/expo/workingdir/build' -> '/Users/expo/workingdir/build/ios/JPARENT'
    at copyFileSync (node:fs:3035:11)
    at setNotificationSounds (/Users/expo/workingdir/build/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:69:31)
    at /Users/expo/workingdir/build/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:43:9
    at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:199:29)
    at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:27)
    at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:204:14)
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
