### ISSUE TITLE
WriteFile return undefined 

### ISSUE THREAD

**Issue by robindesu** [itinance/react-native-fs#816]
I'm trying to save a base64, and get the uri. 
I'm trying to do it on the IOS, but the the writefile is returning undefined for "mySignature" for this code:

`RNFS.writeFile(RNFS.TemporaryDirectoryPath + 'temp.jpg', result.encoded, 'base64').then((mySignature) => {
      console.log("save signature", result.encoded, mySignature);
        ]);`

**Comment by yanavoznuk** [comment]
https://github.com/itinance/react-native-fs#writefilefilepath-string-contents-string-encoding-string-promisevoid - function writeFile return you Promise. It`s you can read in documentation. If you wonted return filePath you can yous this function or write something similar

```
const writeFile = (data, directory) => {
  const fileName = `${Date.now()}_${data.fileName}`;
  const folderPath = `${C.PATH_TO_DIRECTORY}${directory}/${fileName}`;

  return RNFS.writeFile(folderPath, 'contents', 'base64').then(
    () => folderPath,
  );
};

**Comment by robindesu** [comment]
@yanavoznuk Indeed. I would like if this lib returned the saved path on that promise, but I understood that this not gonna happen. Thanks for your reply.
