### ISSUE TITLE
Error: Directory could not be created

### ISSUE THREAD

**Issue by grkemtneri** [itinance/react-native-fs#820]
react-native: 0.61.2
react-native-fs: ^2.16.2

I want to create a new directory in external storage. I expected "Possible Unhandled Promise Rejection (id: 2): Error: Directory could not be created"

here my code 

```
export function createDirCategory(fileName) {
  const file = `${dirHome}/${fileName}`;
    return new Promise((resolve, reject) => {   
    RNFS.mkdir(file)
      .then(() => {
        resolve(true);
      })
      .catch(error => {
        reject(error);
      });
  });
};

```
```
addCategorty() {
    const {categoryName} = this.state;
    createDirCategory(categoryName);
    const folderUrl =getDirUrl(categoryName);
    let id =
      Math.random()
        .toString(36)
        .substring(2) + Date.now().toString(36);
    this.props.changeState;
    store.push('categories', {
      id,
      categoryName,
      imageUrl: [],
      folderUrl,
    });
    this.setState({categoryName: ''});
  }
```

**Comment by embeddedio** [comment]
i have the same issue i can't create folder or file in sdCard with react-native-fs.
i try to create my own library on android but the same issue.
i think the problem is in android.

**Comment by grkemtneri** [comment]
> i have the same issue i can't create folder or file in sdCard with react-native-fs.
> i try to create my own library on android but the same issue.
> i think the problem is in android.

which do you use react native version ?

**Comment by embeddedio** [comment]
> > i have the same issue i can't create folder or file in sdCard with react-native-fs.
> > i try to create my own library on android but the same issue.
> > i think the problem is in android.
> 
> which do you use react native version ?

0.61.5

**Comment by grkemtneri** [comment]
@embeddedio Did you solve the problem?

**Comment by embeddedio** [comment]
@grkemtneri unfortunately not

**Comment by raguct25** [comment]
I have the same issue "Possible Unhandled Promise Rejection (id: 0): Error: Directory could not be created"
