### ISSUE TITLE
Download File not working

### ISSUE THREAD

**Issue by Dellybro** [itinance/react-native-fs#834]
After calling downloadFile, i navigate to my finder open it up and i don't see the file that i downloaded, also RNFS.exists says it doesn't exist as well.

```
const downloadFileResponse = await RNFS.downloadFile({
                fromUrl: media.uri,
                toFile: localPath
            }).promise
            console.log(downloadFileResponse);
```

The output of downloadFile is as follow

{jobId: 8, statusCode: 200, bytesWritten: 0}

**Comment by Dellybro** [comment]
Ok i found out my issue, the uri can't have forward slashes except for the document part

**Comment by FabianTrain** [comment]
> Ok i found out my issue, the uri can't have forward slashes except for the document part

I am not sure if you mean the same but for me it was the local path.
Old:
``` const basePath =
    Platform.OS === 'ios'
      ? RNFS.DocumentDirectoryPath
      : RNFS.ExternalDirectoryPath;
  const localPath = `${basePath}/${folderName}/${filename}`;
``` 
New (working):
``` const basePath =
    Platform.OS === 'ios'
      ? RNFS.DocumentDirectoryPath
      : RNFS.ExternalDirectoryPath;
  const localPath = `${basePath}/${filename}`;
```
