### ISSUE TITLE
Add `symlink` command

### ISSUE THREAD

**Issue by crutchcorn** [itinance/react-native-fs#850]
While the Node.JS API has the following command, `react-native-fs` does not:

https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback

There seems to be support for Windows:
https://docs.microsoft.com/en-us/windows/win32/fileio/symbolic-links

As well as Android:
https://developer.android.com/reference/android/system/Os#symlink(java.lang.String,%2520java.lang.String)

And even iOS as well:
https://developer.apple.com/documentation/foundation/filemanager/1411007-createsymboliclink

**Comment by crutchcorn** [comment]
@itinance I'd like to add this feature to this library. I am looking through the source code and have noticed that `stat` in Android is not implemented using [`Android.Os.stat`](https://developer.android.com/reference/android/system/Os#stat(java.lang.String)) as I might have expected it to be. Is there a reason for this? Should I not use `Os.symlink` for Android support?

**Comment by XilinJia** [comment]
Wonder why this was closed.  Does react-native-fs support symlink?
