### ISSUE TITLE
 sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection

### ISSUE THREAD

**Issue by TrustTheBoy** [itinance/react-native-fs#865]
Device： Android 

function:saveVideo
```
const storeLocation = `${RNFS.DocumentDirectoryPath}`
let pathName = new Date().getTime() + '0714.mp4'
let downloadDest = `${storeLocation}/${pathName}`
const ret = RNFS.downloadFile({
	fromUrl: videoUrl,
	toFile: downloadDest,
})
ret.promise.then(res => {
	if (res && res.statusCode == 200) {
		var promise = CameraRoll.saveToCameraRoll('file://' + downloadDest)
		promise
			.then(result => {
				Toast.showShortCenter('Saved to album')
			})
			.catch(error => {
				Toast.showShortCenter('Save failed')
			})
	}
	console.log(res)
}).catch((error)=>{
	console.log(error)
})
```
```console
 { [Error: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection]
      framesToPop: 1,
      nativeStackAndroid: [],
      userInfo: null,
      code: 'EUNSPECIFIED',
      line: 3059,
      column: 26,
      sourceURL: 'http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false' }
```

**Comment by TrustTheBoy** [comment]
This issue has been resolved

**Comment by mpradas23** [comment]
But how? any reference?

**Comment by LohanaPawan** [comment]
I am facing same issue, could you please help?

**Comment by its-VSP** [comment]
@LohanaPawan , any luck with this issue?

If you've done this please help me out

**Comment by Drckk** [comment]
For me, because I try to download a url like file://xxxx, you should probably call CameraRoll.save() directly

**Comment by shimu12** [comment]
same issue,also don't know how to solve it

**Comment by gustavopch** [comment]
As @Drckk said, in my case it was because I was calling `RNFS.downloadFile` passing a `file://` URI to parameter `fromUrl`. That's not possible. It can't download stuff from the file system.

**Comment by parsable-jobradovic** [comment]
> As @Drckk said, in my case it was because I was calling `RNFS.downloadFile` passing a `file://` URI to parameter `fromUrl`. That's not possible. It can't download stuff from the file system.

you can on ios

**Comment by hieuplasma** [comment]
@TrustDec can you share your solution?

**Comment by TrustDec** [comment]
我已经收到你的邮件啦~,表着急,待我仔细查看
