### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by frtlec** [itinance/react-native-fs#866]
Hi, I am trying to convert the photo in the project to base64

myproject/src/assets/img/aircraftimages/x.jpg

`    var data = 
    await RNFS.readFile("file://../../assets/img/aircraftimages/WingDown_Taildragger_FirewallRef.jpg", 'base64').then(
      res => { return res }
    );
`
running path with Image component why react-native-fs doesn't work

> C:\xh\x\xw\node_modules\react-native\Libraries\YellowBox\YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
Error: ENOENT: /../assets/img/aircraftimages/WingDown_Taildragger_FirewallRef.jpg (No such file or directory), open '../../assets/img/aircraftimages/WingDown_Taildragger_FirewallRef.jpg'
Error: ENOENT: /../assets/img/aircraftimages/WingDown_Taildragger_FirewallRef.jpg (No such file or directory), open '../../assets/img/aircraftimages/WingDown_Taildragger_FirewallRef.jpg'

**Comment by rafa-thayto** [comment]
Hello!

You cannot return the relative path of your source file, because when you are on the device, the path is different...

Instead, you must enter the relative path where you saved the device file, for example:
```js
const data = await RNFS.readFile("file://RELATIVE_DEVICE_PATH/WingDown_Taildragger_FirewallRef.jpg", "base64");
```
If you want to read this file, only on android, you can use the function: `RNFS.readFileAssets()`:
```js
const data = await RNFS.readFileAssets("WingDown_Taildragger_FirewallRef.jpg", "base64");
```

**Comment by frtlec** [comment]
> Hello!
> 
> You cannot return the relative path of your source file, because when you are on the device, the path is different...
> 
> Instead, you must enter the relative path where you saved the device file, for example:
> 
> ```js
> const data = await RNFS.readFile("file://RELATIVE_DEVICE_PATH/WingDown_Taildragger_FirewallRef.jpg", "base64");
> ```
> 
> If you want to read this file, only on android, you can use the function: `RNFS.readFileAssets()`:
> 
> ```js
> const data = await RNFS.readFileAssets("WingDown_Taildragger_FirewallRef.jpg", "base64");
> ```

**Comment by frtlec** [comment]
what is RELATIVE_DEVICE_PATH ?
