### ISSUE TITLE
Autolinking and manual linking for windows.

### ISSUE THREAD

**Issue by branislavantic87** [itinance/react-native-fs#895]
There is no proper documentation to link this library for react native windows. I've followed some other library documentation to link it but in windows folder of library there is no file written in cpp. Auto link and react-native link does not work.

Could someone help me to link this library please.

**Comment by exotexot** [comment]
This article may help you: https://devblogs.microsoft.com/oldnewthing/20200615-00/?p=103868

**Comment by branislavantic87** [comment]
Closing this issue I've figure out along the way, that RNW had a braking change and we have to wait devs to finish C++ support for this library. #868
