### ISSUE TITLE
File persists until restart

### ISSUE THREAD

**Issue by slxsh** [itinance/react-native-fs#908]
Hello, I am deleting a file using RNFS.unlink. However, I am still able to see it until I restart the app. Basically, I have two images, 1.jpg, and 2.jpg. I am deleting the 1.png and renaming the 2.jpg to 1.jpg. Instead of showing the new 1.jpg, I see the original 1.jpg inside my app until I restart the app. I think it's related to cache but I still haven't figured it out.
Here's my delete function
```
function delPic(currentIndex) {  
        RNFS.unlink(RNFS.ExternalDirectoryPath+'/'+name+'/'+currentIndex+'.jpg')  // deleting the image
            .then(async () => {
                if(currentIndex != files.length - 1)
                    for(j = currentIndex+1; j < files.length; j++) { // renaming the remaining images
                       await RNFS.moveFile(RNFS.ExternalDirectoryPath+'/'+name+'/'+j+'.jpg', RNFS.ExternalDirectoryPath+'/'+name+'/'+(j-1)+'.jpg')
                    }
                setVisible(false)
                setReload(!reload) // this will trigger useEffect which reads the directory and updates the state
            })
            .catch(e => console.log(e))
    }
```

**Comment by slxsh** [comment]
It was caused because I wasn't providing a unique key while mapping in the render. I fixed it by changing the naming scheme.

**Comment by AdnanAshraf7** [comment]
can you please mention the name with id of file that you used in your code .. i am facing the same issue and have tried many options but no success .

**Comment by Yangnnnn** [comment]
> can you please mention the name with id of file that you used in your code .. i am facing the same issue and have tried many options but no success .

same issue, have you found a solution ?

**Comment by slxsh** [comment]
@AdnanAshraf7 @Yangnnnn 
Here's the name that I used for my files - 
```js
var date = new Date()
var tempName = 'New Doc '+ date.getFullYear() + '-' + (date.getMonth() + 1) + '-' + date.getDate() + ' ' + date.getHours() + '-' + date.getMinutes() + '-' + date.getSeconds()
var suffix = date.getFullYear().toString() + (date.getMonth() + 1).toString().padStart(2, '0') + date.getDate().toString().padStart(2, '0') + date.getHours().toString().padStart(2, '0') + date.getMinutes().toString().padStart(2, '0') + date.getSeconds().toString().padStart(2, '0') + date.getMilliseconds().toString().padStart(3, '0')
setName(tempName + suffix)
```
You can replace `tempName` with anything you want. Basically, the idea is to have some unique string as a suffix (doesn't have to be a suffix always) and you have to keep the suffix fixed even if you rename the file later on. In this case the unique string is the timestamp of file creation.
Here's the renaming part, If I remember correctly the length of the suffix is 17 - 
```js
RNFS.moveFile(RNFS.ExternalDirectoryPath + '/' + name, RNFS.ExternalDirectoryPath + '/' + nameVal + name.slice(-17))
       .then(() => { setName(nameVal + name.slice(-17)); setRename(false); setNameErr(false) })
       .catch(e => {
            setNameErr(true)
            console.log(e)
       })
```
