### ISSUE TITLE
react-native-fs does not support android 10

### ISSUE THREAD

**Issue by AbdelkaderOumrani** [itinance/react-native-fs#913]
I cannot access RNFS.DownloadDirectoryPath nor ask for permissions to do so

```
await RNFS.readDir(RNFS.DownloadDirectoryPath);
```
in android 8.1 i can access, copy, delete file from this directory
but in android 10, i get this error
**Error: Attempt to get length of null array**

**Comment by AbdelkaderOumrani** [comment]
temporary solution for android 10
```
<manifest ... >
  <!-- This attribute is "false" by default on apps targeting Android Q. -->
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
```

**Comment by Relax594** [comment]
why close this. This is a workaround, not a solution to the main issue.

**Comment by PatrissolJuns** [comment]
@Relax594 indeed, we really need to fix this issue
