### ISSUE TITLE
ENOENT: open failed: EACCES (Permission denied), open '/storage/emulated/0/Download/

### ISSUE THREAD

**Issue by ShivamJoker** [itinance/react-native-fs#941]
I encountered this issue so I am writing this just to tell everyone how to fix this permission issue in android

I have added permissions in manifest file
```xml
....
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> // worked without this also
...
<application ...
android:requestLegacyExternalStorage="true" // this is needed
....
>

```

Also don't forget to ask for permission

```JS
try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
      {
        title: "Cool Photo App Camera Permission",
        message:
          "Your app needs permission.",
        buttonNeutral: "Ask Me Later",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      return true;
    } else {
      console.log("Camera permission denied");
      return false;
    }
  } catch (err) {
    console.warn(err);
    return false;
  }
```

**Comment by wmonecke** [comment]
Stumbled upon this right now!

**Comment by vikil143** [comment]
Hey how do solved this issue

**Comment by vikil143** [comment]
It solved when restarted the app

**Comment by nemishzalavadiya** [comment]
thanks worked for me add well. just do not forget to rebuild the app.

**Comment by Rajan-Savaliya-spt** [comment]
<application ...
android:requestLegacyExternalStorage="true" // this is needed
....
>
 work for me

**Comment by sam9010** [comment]
> <application ...
> android:requestLegacyExternalStorage="true" // this is needed
> ....
> 
> > 
> 
> work for me

android\app\build\intermediates\merged_manifests\debug\arm64-v8a\AndroidManifest.xml:27: AAPT: error: attribute android:requestLegacyExternalStorage not found.

has error

**Comment by gitrthanki1** [comment]
<application ...
android:requestLegacyExternalStorage="true"
....
I make this change but still issue is there it gives me error like ENOENT: open failed: EACCES (Permission denied), open '/storage/emulated/0/Download/config.txt'

**Comment by SohelKabir** [comment]
android:requestLegacyExternalStorage="true" not working api level 30

**Comment by conkyliu** [comment]
android:requestLegacyExternalStorage="true" not working api level 31
PermissionsAndroid=== {android.permission.WRITE_EXTERNAL_STORAGE: 'granted', android.permission.READ_EXTERNAL_STORAGE: 'granted'}

**Comment by mintheinwin** [comment]
<application ...
android:requestLegacyExternalStorage="true"
....
I make this change but still issue is there it gives me error like ENOENT: open failed: EACCES (Permission denied), open '/storage/emulated/0/Download/config.xlsx'

**Comment by SATHISH-001** [comment]
> <application ... android:requestLegacyExternalStorage="true" .... I make this change but still issue is there it gives me error like ENOENT: open failed: EACCES (Permission denied), open '/storage/emulated/0/Download/config.xlsx'

Have you fixed the error for the permission denied?
if you fixed tell me how to fix the error and what was the changes are

**Comment by vikil143** [comment]
```
<application ...
android:requestLegacyExternalStorage="true"
```
Add this and rebuild the app

**Comment by jack828** [comment]
For expo you can use this plugin i wrote to add the tag to `<application>` in a managed workflow.

app.json
```json
"plugins": ["./expo/with-legacy-storage.js"]
```

./expo/with-legacy-storage.js
```js
const { withAndroidManifest } = require('@expo/config-plugins')

module.exports = (config) => {
	const modifyAndroidManifest = (manifest) => {
		const applicationTag = manifest['application'][0]
		applicationTag.$['android:requestLegacyExternalStorage'] = 'true'
		manifest['application'][0] = applicationTag
		return manifest
	}
	return withAndroidManifest(config, async (config) => {
		config.modResults.manifest = modifyAndroidManifest(
			config.modResults.manifest,
		)

		return config
	})
}

```

**Comment by luckyloafer** [comment]
i made all the changes..still the same error

**Comment by conkyliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Pragnesh-Dharajiya** [comment]
<application ...
android:requestLegacyExternalStorage="true">

work for me thanks

**Comment by conkyliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by adityasid** [comment]
> I encountered this issue so I am writing this just to tell everyone how to fix this permission issue in android
> 
> I have added permissions in manifest file
> 
> ```
> ....
>  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> // worked without this also
> ...
> <application ...
> android:requestLegacyExternalStorage="true" // this is needed
> ....
> >
> ```
> 
> Also don't forget to ask for permission
> 
> ```js
> try {
>     const granted = await PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
>       {
>         title: "Cool Photo App Camera Permission",
>         message:
>           "Your app needs permission.",
>         buttonNeutral: "Ask Me Later",
>         buttonNegative: "Cancel",
>         buttonPositive: "OK"
>       }
>     );
>     if (granted === PermissionsAndroid.RESULTS.GRANTED) {
>       return true;
>     } else {
>       console.log("Camera permission denied");
>       return false;
>     }
>   } catch (err) {
>     console.warn(err);
>     return false;
>   }
> ```

Thanks 
Worked for me, Don't forget to rebuild the app

**Comment by conkyliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vijayanand-006** [comment]
Hii EveryOne! , Can someone help me

I'm facing issue on after getting download the pdf it not open properly , it show that cannot display pdf.

**Comment by conkyliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
