### ISSUE TITLE
Question: How to write to File with multiple Lines?

### ISSUE THREAD

**Issue by jawil003** [itinance/react-native-fs#949]
I need to call `writeFile()`  with `content` as a string right? So how I achieve, that I create a new Line in the resulting File? Tried `/n` an d `//n` but didn't seem to work, any Ideas?

**Comment by SilverInfinity** [comment]
A new line can be achieved by using the new line character: `\n`

**Comment by jawil003** [comment]
Sure I accidentally wrote `/n` instead, works fine now.
