### ISSUE TITLE
getting error ERNFS4566769640 - Download has been aborted

### ISSUE THREAD

**Issue by praveens96** [itinance/react-native-fs#976]
Hi,
in a specific instance I am getting the below error:

> [
>   "Download 1 err res",
>   {
>     "code": "ERNFS4566769640",
>     "message": "Download has been aborted",
>     "domain": "RNFS",
>     "userInfo": {
>       "NSLocalizedDescription": "Download has been aborted"
>     },
>     "nativeStackIOS": [
>       "0   proj                             0x000000010f228327 RCTJSErrorFromCodeMessageAndNSError + 135",
>       "1   proj                             0x000000010f1b0ad3 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 179",
>       "2   proj                             0x000000010f0817aa -[RNFSManager reject:withError:] + 330",
>       "3   proj                             0x000000010f07d6c4 __46-[RNFSManager downloadFile:resolver:rejecter:]_block_invoke.219 + 148",
>       "4   proj                             0x000000010f077da3 -[RNFSDownloader stopDownload] + 419",
>       "5   proj                             0x000000010f07dde6 -[RNFSManager stopDownload:] + 198",
>       "6   CoreFoundation                      0x00007fff204272fc __invoking___ + 140",
>       "7   CoreFoundation                      0x00007fff204247b6 -[NSInvocation invoke] + 303",
>       "8   CoreFoundation                      0x00007fff20424a47 -[NSInvocation invokeWithTarget:] + 70",
>       "9   proj                             0x000000010f1b26e4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2660",
>       "10  proj                             0x000000010f1b688e _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 814",
>       "11  proj                             0x000000010f1b6356 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 134",
>       "12  proj                             0x000000010f1b62bc ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28",
>       "13  libdispatch.dylib                   0x00007fff2010532f _dispatch_call_block_and_release + 12",
>       "14  libdispatch.dylib                   0x00007fff20106508 _dispatch_client_callout + 8",
>       "15  libdispatch.dylib                   0x00007fff2010c3f9 _dispatch_lane_serial_drain + 715",
>       "16  libdispatch.dylib                   0x00007fff2010cf74 _dispatch_lane_invoke + 403",
>       "17  libdispatch.dylib                   0x00007fff20117577 _dispatch_workloop_worker_thread + 782",
>       "18  libsystem_pthread.dylib             0x00007fff60c8e499 _pthread_wqthread + 314",
>       "19  libsystem_pthread.dylib             0x00007fff60c8d467 start_wqthread + 15"
>     ]
>   },
>   null
> ]

in most of the places its working fine. this is coming when trying to download a file as below

`RNFS.downloadFile({
        fromUrl: url,
        toFile: filePath,
        background: true,
        cacheable: false,
        progressDivider: 1,
        begin: beginCallback,
        progress: progressCallback,
        connectionTimeout: 300000,
        readTimeout: 300000,
    })
    .promise.then(res => {
            doneCallback(null, { ...res, filePath, filename });
        })
        .catch(err => {
            doneCallback(err, null);
        });`

**Comment by praveens96** [comment]
this got fixed after giving proper keyExtractor to my flatlist. not Sure of the relation between my component and RNFS but it worked.

**Comment by hushaudio** [comment]
Its possible that when the Flatlist looses track of the propper keys for each component they end their life cycle randomly (depending on how messed up the keys are).  When the components cycle ends, any functions running inside it will be deleted/GC'd
