### ISSUE TITLE
@2.16.0 doesnt exist

### ISSUE THREAD

**Issue by septe01** [itinance/react-native-fs#977]
my react native version
"react-native": "0.62.2"

when install pakcage use npm i react-native-fs@2.16.0

error No matching version found for react-native-fs@2.16.0.

**Comment by bjurij** [comment]
https://github.com/itinance/react-native-fs/tags

**Comment by webraptor** [comment]
@itinance can we get the latest version released properly in npm? last release is quite old now.

**Comment by itinance** [comment]
Done. Thanks for the reminder!
