### ISSUE TITLE
Is there any restriction on react-native-fs to obtain local static resource files?

### ISSUE THREAD

**Issue by mofengfs** [itinance/react-native-fs#979]
> Workable short code

![image](https://user-images.githubusercontent.com/16655229/107481095-97ced080-6bb8-11eb-9243-36ea25e70c4a.png)
![image](https://user-images.githubusercontent.com/16655229/107477211-53403680-6bb2-11eb-9a98-b3885b11ca68.png)

> Can't work short code

![image](https://user-images.githubusercontent.com/16655229/107477295-74a12280-6bb2-11eb-93d3-1f4ab4e835d4.png)

> error

![image](https://user-images.githubusercontent.com/16655229/107476908-c1382e00-6bb1-11eb-8c35-ecce39d7afad.png)

> Can't work short code 

![image](https://user-images.githubusercontent.com/16655229/107481671-8934e900-6bb9-11eb-9022-435d29fd918a.png)

> error

![image](https://user-images.githubusercontent.com/16655229/107481745-ac5f9880-6bb9-11eb-9042-f2ea3c3235e3.png)

**Comment by mofengfs** [comment]
I know the reason, I need to uninstall the app clean and restart yarn android

**Comment by Yasir12598** [comment]
@codthing  Try this it works for me.
```
import {view, StyleSheet, PermissionsAndroid} from from 'react-native';

PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
    PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE);
```
