### ISSUE TITLE
Android Plugin Issue

### ISSUE THREAD

**Issue by Anukr98** [itinance/react-native-fs#980]
My project was working perfectly yesterday. Today when I tried syncing it on Studio, it said -
Could not find com.android.tools.build:gradle:4.0.1.
Searched in the following locations:
  - https://jcenter.bintray.com/com/android/tools/build/gradle/4.0.1/gradle-4.0.1.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :react-native-fs

Upgrading the plugin version to 4.1.0 did not help either.
Anyone have a workaround for this?

**Comment by ghcordeiro** [comment]
for me it worked by adding the google () dependency in the library's build.gradle
![2021-03-03_15h09_56](https://user-images.githubusercontent.com/47925605/109851524-8a928800-7c32-11eb-9352-bef34ea5c463.png)

**Comment by jplandry908** [comment]
Thanks @ghcordeiro. I was having the same issue and adding "google()" fixed it for me.

**Comment by Anukr98** [comment]
@ghcordeiro , surprisingly the issue was fixed automatically for me after almost a day. It seems AGP and Maven repo servers must have been down for some time due to which it kept giving me 403 errors.
PS: google() was already listed as a dependency for me.
